"use client";
import {Brand} from "@/components/brand";
import {useState} from "react";
import {Compass,ArrowRight,ShieldCheck,BookOpen,Flower2} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {ErrorBox} from "@/components/common";
import {write,errorText} from "@/lib/client";
export default function Login(){const [error,setError]=useState(""),[busy,setBusy]=useState(false);return <main className="login-page"><section className="login-story"><div className="brand"><Brand/></div><div><p className="eyebrow">Du CP au CM2</p><h1>Les grandes découvertes<br/>commencent par<br/><span>un petit pas.</span></h1><p>Un endroit pour essayer, poser des questions<br/>et apprendre à ton rythme.</p><div className="login-path" aria-hidden="true"><span><BookOpen/></span><i/><span><Compass/></span><i/><span><Flower2/></span></div><div className="login-photo"><img src="/login-carret.jpg" alt="La mascotte de BoostClasse, un élève cubique qui salue, prêt à explorer de nouvelles leçons" width="640" height="357"/></div></div><p className="login-foot">Avec Capitaine Savoir, cherche le chemin.</p></section><section className="login-form"><div className="login-form-inner"><p className="eyebrow">Ravi de te retrouver</p><h2>Prêt pour la suite ?</h2><p>Choisis ta classe et connecte-toi à ton profil.</p>{error&&<ErrorBox message={error}/>}<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);try{const result=await write<{redirect:string}>("session",Object.fromEntries(f));window.location.assign(result.redirect);}catch(e){setError(errorText(e));}finally{setBusy(false);}}}><label htmlFor="level">Ta classe</label><select id="level" name="level" required defaultValue="CM2"><option value="CP">CP</option><option value="CE1">CE1</option><option value="CE2">CE2</option><option value="CM1">CM1</option><option value="CM2">CM2</option></select><label htmlFor="login">Ton identifiant</label><Input id="login" name="login" required autoComplete="username" autoCapitalize="none" spellCheck={false}/><label htmlFor="password">Ton mot de passe</label><Input id="password" name="password" type="password" required autoComplete="current-password"/><Button type="submit" disabled={busy} className="w-full">{busy?"Connexion…":"Entrer dans mon espace"}<ArrowRight size={19}/></Button></form><p className="login-help">Un accès perdu ? Demande à ton enseignant ou à l’administrateur de l’école.</p><p className="privacy-note"><ShieldCheck size={20}/> Ton espace est personnel et protégé.</p></div></section></main>;}
