"use client";
import {useState} from "react";
import {MathDiagram} from "./math-diagram";
import "./math-workshop.css";
import {ArrowUp,ArrowDown,GripVertical} from "lucide-react";
import {Button} from "./ui/button";
import {Input} from "./ui/input";
import type {Answers,Exercise,Part} from "@/lib/contracts";
import {moveItem} from "@/lib/journey";
function Order({part,value,onChange,disabled,timeline}:{part:Part;value:string|string[]|undefined;onChange:(value:string[])=>void;disabled:boolean;timeline:boolean}) {
  const items=Array.isArray(value)?value:part.options.map(o=>o.id),[drag,setDrag]=useState<number|null>(null),[announcement,setAnnouncement]=useState("");
  function move(from:number,to:number){onChange(moveItem(items,from,to));setAnnouncement(`Élément déplacé à la position ${to+1}.`);}
  return <div><p className="hint-text">{timeline?"Du plus ancien au plus récent.":"Place les éléments dans le bon ordre."} Utilise les flèches ou déplace les cartes.</p><ol className={timeline?"order-list timeline":"order-list"}>{items.map((id,i)=><li key={id} draggable={!disabled} onDragStart={e=>{setDrag(i);e.dataTransfer.setData("text/plain",id);}} onDragEnd={()=>setDrag(null)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(drag!==null)move(drag,i);setDrag(null);}}><span className="order-number" aria-hidden="true">{i+1}</span><GripVertical size={16} aria-hidden="true"/><span className="order-label">{part.options.find(o=>o.id===id)?.label}</span><Button type="button" variant="ghost" disabled={disabled||i===0} onClick={()=>move(i,i-1)} aria-label={`Monter ${part.options.find(o=>o.id===id)?.label}`}><ArrowUp size={18}/></Button><Button type="button" variant="ghost" disabled={disabled||i===items.length-1} onClick={()=>move(i,i+1)} aria-label={`Descendre ${part.options.find(o=>o.id===id)?.label}`}><ArrowDown size={18}/></Button></li>)}</ol><span role="status" className="sr-only">{announcement}</span></div>;
}
export function ExerciseFields({exercise,answers,onAnswer,disabled=false}:{exercise:Exercise;answers:Answers;onAnswer:(id:string,value:string|string[])=>void;disabled?:boolean}) {
  return <div className="exercise-fields">{exercise.prompt.parts.map((p,i)=><fieldset key={p.id} disabled={disabled}><legend><span className="question-number">{i+1}</span>{p.question}</legend>{p.visual&&<MathDiagram visual={p.visual}/>} {p.response_type==="choice"?<div className="choice-grid">{p.options.map(o=><label key={o.id} className={`choice ${answers[p.id]===o.id?"chosen":""}`}><input type="radio" name={p.id} value={o.id} checked={answers[p.id]===o.id} onChange={()=>onAnswer(p.id,o.id)}/><span>{o.label}</span></label>)}</div>:p.response_type==="ordering"?<Order part={p} value={answers[p.id]} onChange={v=>onAnswer(p.id,v)} disabled={disabled} timeline={exercise.kind==="timeline"}/>:<div><label className="sr-only" htmlFor={`answer-${p.id}`}>{p.response_type==="number"?"Ta réponse numérique":"Ta réponse"} : {p.question}</label>{p.response_type==="text"?<textarea id={`answer-${p.id}`} autoComplete="off" maxLength={512} rows={3} value={typeof answers[p.id]==="string"?answers[p.id] as string:""} onChange={e=>onAnswer(p.id,e.target.value)} placeholder="Écris ta réponse"/>:<Input id={`answer-${p.id}`} autoComplete="off" maxLength={512} inputMode={p.response_type==="number"?"decimal":"text"} value={typeof answers[p.id]==="string"?answers[p.id] as string:""} onChange={e=>onAnswer(p.id,e.target.value)} placeholder={p.response_type==="number"?"Écris un nombre":"Écris ta réponse"}/>}{p.response_type==="number"&&<p className="hint-text">Tu peux utiliser une virgule pour les décimales.</p>}</div>}</fieldset>)}</div>;
}
export function completeAnswers(exercise:Exercise,answers:Answers):Answers{return Object.fromEntries(exercise.prompt.parts.map(p=>[p.id,answers[p.id]??(p.response_type==="ordering"?p.options.map(o=>o.id):"")]));}
