"use client";
import {useState} from "react";
import {useApi,ErrorBox,Loading} from "./common";
import {Button} from "./ui/button";
import {Card} from "./ui/card";
import {api,write,errorText} from "@/lib/client";
import type {Account} from "@/lib/contracts";
type Course={id:string;version:number;title:string;status:string;author_id:string;body:{cm2:{objective:string;prerequisites:string[];discovery:string;explanation:string;method:string[];worked_example:string[];common_errors:string[];check_exercise_id:string;practice_exercise_ids:string[]}}};
type Exercise={id:string;exercise_id:string;version:number;status:string;candidate:{instruction:string;parts:{options:{id:string;label:string}[]}[];hints:{level:number;text:string}[];answers:Record<string,{expected:unknown;solution_steps:string[]}>}};
export function FrenchEditorial({account}:{account:Account}) {
 const [open,setOpen]=useState(false);const data=useApi<{courses:Course[]}>(open?"content/french/review-catalogue":null),[selected,setSelected]=useState("");
 const course=data.data?.courses.find(c=>c.id===selected)||data.data?.courses[0];
 return <section><Button variant="outline" onClick={()=>setOpen(!open)}>Relire et publier les parcours de français</Button>{open&&<Card><h2>Les parcours de français CM2</h2><p>Chaque dossier contient une leçon, une mini-question, deux exercices, leurs indices et leurs corrections. La publication devient effective après ta relecture.</p>{data.loading?<Loading/>:data.error?<ErrorBox message={data.error}/>:<><p>{data.data?.courses.filter(c=>c.status==="approved").length} / {data.data?.courses.length} parcours publiés</p><label htmlFor="french-review">Dossier à relire</label><select id="french-review" value={course?.id||""} onChange={e=>setSelected(e.target.value)}>{data.data?.courses.map(c=><option key={c.id} value={c.id}>{c.title} · {c.status==="approved"?"Publié":"À relire"}</option>)}</select>{course&&<Review key={course.id} course={course} account={account} done={data.reload}/>}</>}</Card>}</section>;
}
function Review({course,account,done}:{course:Course;account:Account;done:()=>void}) {
 const c=course.body.cm2,[exercises,setExercises]=useState<Exercise[]>([]),[error,setError]=useState(""),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false);
 const canReview=account.roles.some(r=>r==="teacher"||r==="content_creator")&&account.id!==course.author_id;
 async function load(){setBusy(true);setError("");try{setExercises(await Promise.all([c.check_exercise_id,...c.practice_exercise_ids].map(id=>api<Exercise>(`exercise/review-version/${id}`))));}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 async function publish(){setBusy(true);setError("");try{for(const ex of exercises){const current=await api<Exercise>(`exercise/review-version/${ex.id}`);if(current.status!=="published")await write(`exercise/exercises/${ex.exercise_id}/versions/${ex.version}/reviews`,{decision:"approved",reason_code:"FRENCH_HUMAN_REVIEW",confirmed_human_review:true});}await write(`content/contents/${course.id}/versions/${course.version}/reviews`,{decision:"approved",reason_code:"FRENCH_HUMAN_REVIEW",confirmed_human_review:true});done();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 return <article><h3>{course.title}</h3><p><strong>Objectif : </strong>{c.objective}</p><h4>Prérequis</h4><ul>{c.prerequisites.map(x=><li key={x}>{x}</li>)}</ul><h4>Découverte</h4><p>{c.discovery}</p><h4>Explication</h4><p>{c.explanation}</p><h4>Méthode</h4><ol>{c.method.map(x=><li key={x}>{x}</li>)}</ol><h4>Exemple résolu</h4>{c.worked_example.map(x=><p key={x}>{x}</p>)}<h4>Erreurs fréquentes</h4><ul>{c.common_errors.map(x=><li key={x}>{x}</li>)}</ul><p><a href="https://www.education.gouv.fr/sites/default/files/programme-de-fran-ais-pour-le-cycle-3-439824.pdf" target="_blank" rel="noreferrer">Référentiel : programme de français du cycle 3</a></p><Button variant="outline" disabled={busy} onClick={()=>void load()}>Examiner les trois exercices et leurs corrections</Button>{exercises.map((ex,i)=><section key={ex.id}><h4>{i===0?"Mini-question":`Exercice ${i}`}</h4><p>{ex.candidate.instruction}</p><ul>{ex.candidate.parts.flatMap(p=>p.options).map(o=><li key={o.id}>{o.label}</li>)}</ul>{ex.candidate.hints.map(h=><p key={h.level}>Indice {h.level} : {h.text}</p>)}{Object.values(ex.candidate.answers).flatMap(a=>a.solution_steps).map((s,j)=><p key={j}>Correction : {s}</p>)}</section>)}{course.status==="approved"?<p role="status">Ce parcours est publié et accessible aux élèves.</p>:!canReview?<p>La validation se fait avec un compte enseignant indépendant de l’auteur, par exemple prof.master.</p>:exercises.length===3&&<><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> J’ai relu la leçon, les trois exercices et leurs corrections et je les valide pour les élèves.</label><Button disabled={!confirmed||busy} onClick={()=>void publish()}>{busy?"Publication…":"Valider et publier ce parcours"}</Button></>}{error&&<ErrorBox message={error}/>}</article>;
}
