"use client";
import {useState} from "react";
import {Clock3,MapPin,FileSearch,Users,ArrowRight,Volume2} from "lucide-react";
import type {HistoryChapter,HistorySource} from "@/lib/history";
import {Button} from "./ui/button";
import "./history-workshop.css";

function Reference({source}:{source:HistorySource}) {return <p className="history-reference"><a href={source.url} target="_blank" rel="noreferrer">{source.title} ↗</a>{source.page?` · p. ${source.page}`:""}<span>{source.section}</span></p>;}
export function HistoryExplorer({chapter}:{chapter:HistoryChapter}) {
  const [tab,setTab]=useState("frise"),[selected,setSelected]=useState(0),[place,setPlace]=useState(0),[question,setQuestion]=useState(0),[notes,setNotes]=useState<string[]>(["","",""]),[showLimits,setShowLimits]=useState(false);
  const event=chapter.timeline[selected],doc=chapter.document,p=chapter.places[place];
  function speak(text:string){if(typeof window!=="undefined"&&"speechSynthesis" in window){window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang="fr-FR";window.speechSynthesis.speak(utterance);}}
  return <section className="history-explorer" aria-label="Les outils de l’historien">
    <header><p className="history-kicker">LES OUTILS DE L’HISTORIEN</p><h3>{chapter.period}</h3><p>{chapter.essential_question}</p></header>
    <div className="history-tools" role="tablist" aria-label="Explorer les indices">{[{id:"frise",label:"La frise",Icon:Clock3},{id:"lieux",label:"Les lieux",Icon:MapPin},{id:"personnages",label:"Les personnes",Icon:Users},{id:"document",label:"Le document",Icon:FileSearch}].map(({id,label,Icon})=><button key={id} id={`history-tab-${id}`} role="tab" aria-controls="history-panel" aria-selected={tab===id} onClick={()=>setTab(id)}><Icon size={17}/>{label}</button>)}</div>
    <div id="history-panel" role="tabpanel" aria-labelledby={`history-tab-${tab}`} className="history-panel">
    {tab==="frise"&&<><p>Choisis un repère pour découvrir ce qu’il signifie.</p><ol className="history-timeline">{chapter.timeline.map((e,i)=><li key={e.id}><button onClick={()=>setSelected(i)} aria-pressed={selected===i}><span>{e.date}</span><strong>{e.title}</strong></button></li>)}</ol><p className="history-caption">Repères dans l’ordre chronologique. Les espacements sont adaptés à la lecture et ne représentent pas les durées.</p><div className="history-evidence" aria-live="polite"><p className="history-kicker">ÉVÉNEMENT · {event.date}</p><h4>{event.title}</h4><p>{event.explanation}</p><Reference source={event.source}/></div><div className="history-cause-grid"><div><h4>Ce qui aide à comprendre</h4>{chapter.causes.map(v=><p key={v}>{v}</p>)}</div><ArrowRight aria-hidden="true"/><div><h4>Ce qui change ensuite</h4>{chapter.consequences.map(v=><p key={v}>{v}</p>)}</div></div></>}
    {tab==="lieux"&&<><p>Ces points situent approximativement les lieux. Ils ne dessinent pas les frontières de l’époque.</p><div className="history-map" aria-label="Repères géographiques en Europe"><svg viewBox="0 0 600 300" role="img" aria-label="Grille de localisation entre 10 degrés ouest et 20 degrés est, de 35 à 60 degrés nord"><defs><pattern id="history-grid" width="60" height="60" patternUnits="userSpaceOnUse"><path d="M60 0H0V60" fill="none" stroke="currentColor" opacity=".18"/></pattern></defs><rect width="600" height="300" fill="url(#history-grid)"/><text x="12" y="25">N ↑</text><text x="12" y="286">10° O</text><text x="550" y="286">20° E</text>{chapter.places.map((item,i)=><g key={item.name}><circle cx={(item.longitude+10)*20} cy={(60-item.latitude)*12} r={i===place?10:6} fill={i===place?"#ad562f":"#28665d"}/><text x={(item.longitude+10)*20+15} y={(60-item.latitude)*12+4}>{item.name}</text></g>)}</svg></div><div className="history-location-buttons">{chapter.places.map((item,i)=><button key={item.name} aria-pressed={place===i} onClick={()=>setPlace(i)}><MapPin size={16}/>{item.name}</button>)}</div><h4>{p.name}</h4><p>{p.importance}</p><Reference source={p.source}/></>}
    {tab==="personnages"&&<>{chapter.figures.length?chapter.figures.map(f=><article key={f.name} className="history-figure"><div className="history-initial" aria-hidden="true">{f.name.split(" ").map(n=>n[0]).join("")}</div><div><p className="history-kicker">{f.born}–{f.died}</p><h4>{f.name}</h4><p>{f.role}</p><p><strong>À retenir :</strong> {f.remember}</p><p><strong>À ne pas confondre :</strong> {f.confusion}</p><Reference source={f.source}/></div></article>):<p>Ce dossier étudie surtout des groupes de personnes et des changements dans la société. Il ne se résume pas à un seul personnage.</p>}</>}
    {tab==="document"&&<><div className="history-document"><p className="history-kicker">{doc.type} · {doc.presentation}</p><h4>{doc.title}</h4><dl><div><dt>Date</dt><dd>{doc.date}</dd></div><div><dt>Origine</dt><dd>{doc.origin}</dd></div></dl><p>{doc.context}</p>{doc.presentation==="court extrait"?<blockquote>« {doc.content} »</blockquote>:<p className="history-document-text">{doc.content}</p>}<Reference source={doc.source}/></div><div className="history-investigate"><p className="history-kicker">À TOI D’OBSERVER · {question+1}/3</p><label htmlFor="history-observation">{doc.questions[question]}</label><textarea id="history-observation" maxLength={1000} value={notes[question]} onChange={e=>setNotes(old=>old.map((v,i)=>i===question?e.target.value:v))} placeholder="Je m’appuie sur…"/><p className="history-caption">Brouillon de réflexion pour cette lecture. Tu enregistreras ta réponse dans les défis qui suivent.</p><Button variant="outline" disabled={!notes[question].trim()} onClick={()=>question<2?setQuestion(question+1):setShowLimits(true)}>{question<2?"Observer un autre indice":"Comparer avec les limites du document"}</Button>{question>0&&<Button variant="outline" onClick={()=>setQuestion(question-1)}>Question précédente</Button>}{showLimits&&<div aria-live="polite"><h4>Ce que l’on peut dire</h4><p>{doc.shows}</p><h4>Ce que l’on ne peut pas prouver</h4><p>{doc.limits}</p></div>}</div></>}
    </div>
    <details className="history-words"><summary>Les mots pour comprendre · {chapter.vocabulary.length} mots</summary><dl>{chapter.vocabulary.map(v=><div key={v.word}><dt>{v.word}</dt><dd>{v.definition}</dd></div>)}</dl></details>
    <details className="history-words"><summary>Besoin de reprendre doucement ?</summary>{chapter.remediation.map(line=><p key={line}>{line}</p>)}</details>
    <button className="history-read" onClick={()=>speak(tab==="document"?doc.content:event.explanation)}><Volume2 size={16}/>Lire ce repère à voix haute</button>
  </section>;
}
