"use client";
import {useEffect,useState} from "react";
import {Heart,Mail,Check} from "lucide-react";
import {useApi,PageTitle,Loading,ErrorBox,Empty} from "./common";
import type {Student,Progress,Notice} from "@/lib/contracts";
import {Card} from "./ui/card";
import {Button} from "./ui/button";
import {Privacy} from "./privacy";
import {ScienceNotebook} from "./science-library";
import {ProgressCards} from "./progress";
import {api,write,errorText} from "@/lib/client";
export function ParentSpace(){const students=useApi<Student[]>("user/students"),[selected,setSelected]=useState(""),[tab,setTab]=useState("progress"),id=selected||students.data?.[0]?.id;return <><PageTitle eyebrow="Espace parent" title="Grandir, un apprentissage à la fois.">Un regard bienveillant sur son chemin, et des idées pour l’accompagner.</PageTitle>{students.loading?<Loading/>:students.error?<ErrorBox message={students.error} retry={students.reload}/>:!students.data?.length?<Card><Empty title="Aucun enfant n’est encore lié à votre compte."><p>L’établissement doit vérifier votre lien de responsabilité avant d’ouvrir l’accès à son suivi.</p></Empty></Card>:<><div className="toolbar"><label htmlFor="child">Le carnet de</label><select id="child" value={id} onChange={e=>setSelected(e.target.value)}>{students.data.map(s=><option key={s.id} value={s.id}>{s.pseudonym} · {s.level}</option>)}</select></div><div className="tab-buttons" aria-label="Rubriques parent">{[{id:"progress",label:"Son chemin"},{id:"reports",label:"Rapports hebdomadaires"},{id:"privacy",label:"Confidentialité & audio"}].map(t=><Button key={t.id} variant={tab===t.id?"default":"outline"} aria-pressed={tab===t.id} onClick={()=>setTab(t.id)}>{t.label}</Button>)}</div>{id&&(tab==="privacy"?<Privacy key={id} studentId={id}/>:tab==="reports"?<Reports studentId={id}/>:<ParentProgress key={id} studentId={id}/>)}</>}</>;}
function ParentProgress({studentId}:{studentId:string}){const [days,setDays]=useState("7"),progress=useApi<Progress>(`analytics/students/${studentId}/dashboard?days=${days}`);return <div className="stack"><div className="toolbar"><label htmlFor="period">Période d’activité</label><select id="period" value={days} onChange={e=>setDays(e.target.value)}><option value="7">Les 7 derniers jours</option><option value="30">Les 30 derniers jours</option></select></div>{progress.loading?<Loading/>:progress.error?<ErrorBox message={progress.error} retry={progress.reload}/>:progress.data&&<><ProgressCards data={progress.data}/><Skills studentId={studentId}/><ScienceNotebook key={studentId} studentId={studentId} readOnly/><Card className="home-ideas"><Heart/><div><p className="eyebrow">Une idée pour la maison</p><h2>{progress.data.competences_a_retravailler?"Cinq minutes pour expliquer ensemble.":"Laissez votre enfant vous apprendre quelque chose."}</h2><p>{progress.data.competences_a_retravailler?"Choisissez une activité récente. Demandez : « Qu’as-tu essayé ? Qu’est-ce qui t’a aidé ? » Relisez la consigne ensemble, puis laissez-lui le temps de chercher.":"Invitez-le à raconter une découverte ou à montrer une méthode, avec ses mots. Valorisez sa démarche et ses questions."}</p><p className="hint-text">Suggestion générale d’accompagnement, à adapter avec l’enseignant.</p></div></Card></>}</div>;}
export function Reports({studentId}:{studentId?:string}) {const reports=useApi<Notice[]>("notification/inbox?limit=100"),[error,setError]=useState("");const filtered=reports.data?.filter(n=>!studentId||n.student_id===studentId);return <Card><h2><Mail className="inline-icon"/> La boîte de nouvelles</h2><p>Les rapports sont disponibles ici pendant 30 jours.</p>{reports.loading?<Loading/>:reports.error?<ErrorBox message={reports.error} retry={reports.reload}/>:!filtered?.length?<Empty title="Pas encore de nouvelles."><p>Les rapports apparaîtront après le premier envoi hebdomadaire de l’établissement.</p></Empty>:<div className="report-list">{filtered.map(n=><article key={n.id}><p className="eyebrow">{n.kind==="weekly_report"?"Rapport hebdomadaire":"Un accompagnement à proposer"} · {new Date(n.period+"T12:00:00").toLocaleDateString("fr-FR")}</p><h3>{n.body.message||"Chaque séance permet d’avancer à son rythme."}</h3>{n.kind==="weekly_report"&&<p>{n.body.minutes_session_estimees??0} minutes de sessions estimées · {n.body.tentatives_terminees??0} activités terminées.</p>}{n.read_at?<span className="pill"><Check size={14}/> Lu</span>:<Button variant="outline" onClick={async()=>{try{await write(`notification/inbox/${n.id}/read`,{});reports.reload();}catch(e){setError(errorText(e));}}}>Marquer comme lu</Button>}</article>)}</div>}{error&&<ErrorBox message={error}/>}</Card>;}

function Skills({studentId}:{studentId:string}) {
  const [items,setItems]=useState<{id:string;label:string;level:string}[]>([]),[error,setError]=useState("");
  useEffect(()=>{let alive=true;api<{competency_id:string;level:string}[]>(`assessment/students/${studentId}/mastery?limit=10`).then(async rows=>Promise.all(rows.map(async row=>({id:row.competency_id,level:row.level,...await api<{label:string}>(`curriculum/competencies/${row.competency_id}`)})))).then(value=>{if(alive)setItems(value);}).catch(e=>{if(alive)setError(errorText(e));});return()=>{alive=false;};},[studentId]);
  return <Card><h2>Les compétences travaillées</h2><p>Jusqu’à dix compétences à revoir ou à entretenir, selon les prochaines révisions.</p>{error?<ErrorBox message={error}/>:!items.length?<p>Les premières compétences apparaîtront après les activités.</p>:<ul className="history-list">{items.map(x=><li key={x.id}><span>{x.label}</span><span className="pill">{({fragile:"À reprendre",en_cours:"En apprentissage",maîtrisé:"Acquise",consolidé:"Consolidée",découverte:"Découverte",non_evalué:"À découvrir"} as Record<string,string>)[x.level]||x.level}</span></li>)}</ul>}</Card>;
}
