"use client";
import {useState} from "react";
import {ShieldCheck} from "lucide-react";
import type {Policy,Consent,Student,Preferences} from "@/lib/contracts";
import {useApi,ErrorBox,Loading} from "./common";
import {Card} from "./ui/card";
import {Button} from "./ui/button";
import {write,errorText} from "@/lib/client";
const names:Record<string,string>={ai_local:"Aide IA locale",ai_cloud:"Aide IA externe",voice:"Lecture audio"};
export function Privacy({studentId,child=false}:{studentId:string;child?:boolean}) {
  const policy=useApi<Policy>("user/consent-policy"),permissions=useApi<Record<string,boolean>>(`user/students/${studentId}/permissions`),history=useApi<Consent[]>(child?null:`user/students/${studentId}/consents`),profile=useApi<Student>(`user/students/${studentId}`);
  const [understood,setUnderstood]=useState<Record<string,boolean>>({}),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
  async function choose(purpose:string,granted:boolean){if(!policy.data)return;setBusy(true);setError("");setNotice("");try{await write(child?"user/me/assents":`user/students/${studentId}/consents`,child?{purpose,policy_version:policy.data.version,agreed:granted}:{purpose,policy_version:policy.data.version,granted,understood:understood[purpose]===true});permissions.reload();history.reload();setNotice(granted?"Ton choix a été enregistré.":"Le refus a été enregistré. Cette option reste désactivée.");}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  return <div className="stack"><Card><div className="section-heading"><h2><ShieldCheck className="inline-icon"/> {child?"Tu peux choisir tes aides":"Confidentialité et aides facultatives"}</h2></div>{policy.loading?<Loading/>:policy.error?<ErrorBox message={policy.error} retry={policy.reload}/>:policy.data&&<><p>{child?policy.data.child_notice:policy.data.withdrawal}</p><p className="hint-text">Une option fonctionne uniquement lorsque le parent et l’enfant ont donné leur accord. L’enseignant peut également limiter l’aide IA.</p>{Object.entries(policy.data.purposes).map(([key,description])=><div key={key} className="consent-row"><div><h3>{names[key]||key}</h3><p>{description}</p><span className="pill">{permissions.data?.[key]?"Accords réunis":"Option non autorisée"}</span></div><div>{!child&&<label className="checkbox-label"><input type="checkbox" checked={!!understood[key]} onChange={e=>setUnderstood(x=>({...x,[key]:e.target.checked}))}/> J’ai compris cet usage facultatif.</label>}<div className="button-row"><Button disabled={busy||(!child&&!understood[key])} onClick={()=>void choose(key,true)}>{child?"Je suis d’accord":"Autoriser"}</Button><Button variant="outline" disabled={busy} onClick={()=>void choose(key,false)}>{child?"Je ne suis pas d’accord":"Refuser / retirer"}</Button></div></div></div>)}</>}{error&&<ErrorBox message={error}/>}<p role="status">{notice}</p></Card>{profile.data&&!child&&<PreferenceForm key={studentId} student={profile.data}/>} {!child&&<Card><h2>Historique des choix parentaux</h2>{history.error?<ErrorBox message={history.error}/>:!history.data?.length?<p>Aucun choix parental n’est enregistré.</p>:<ul className="history-list">{history.data.slice(0,20).map(c=><li key={c.id}><span>{names[c.purpose]||c.purpose} · {c.granted?"Autorisation":"Refus ou retrait"}</span><time>{new Date(c.recorded_at).toLocaleDateString("fr-FR")}</time></li>)}</ul>}</Card>}</div>;
}
function PreferenceForm({student}:{student:Student}) {const [value,setValue]=useState<Preferences>({text_size:student.accessibility_preferences.text_size||"normal",dyslexic_font:!!student.accessibility_preferences.dyslexic_font,voice_instructions:!!student.accessibility_preferences.voice_instructions}),[notice,setNotice]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);return <Card><h2>Confort de lecture de {student.pseudonym}</h2><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");try{await write(`user/students/${student.id}/preferences`,value,"PUT");setNotice("Préférences enregistrées.");}catch(e){setError(errorText(e));}finally{setBusy(false);}}}><label className="checkbox-label"><input type="checkbox" checked={value.text_size==="large"} onChange={e=>setValue(v=>({...v,text_size:e.target.checked?"large":"normal"}))}/> Agrandir le texte</label><label className="checkbox-label"><input type="checkbox" checked={value.dyslexic_font} onChange={e=>setValue(v=>({...v,dyslexic_font:e.target.checked}))}/> Aérer la lecture et les espacements</label><p className="hint-text">La police Atkinson Hyperlegible est intégrée à l’application. Le confort varie selon chaque lecteur.</p><Button disabled={busy}>Enregistrer le confort de lecture</Button><p role="status">{notice}</p>{error&&<ErrorBox message={error}/>}</form></Card>;}
