"use client";
import {useState,useEffect} from "react";
import {Users,Plus,Compass,ShieldCheck} from "lucide-react";
import {useApi,PageTitle,Loading,Empty,ErrorBox} from "./common";
import {Button} from "./ui/button";
import {Input} from "./ui/input";
import {Card} from "./ui/card";
import {ProgressBars} from "./progress";
import {FrenchEditorial} from "./french-editorial";
import {HistoryEditorial} from "./history-editorial";
import {ScienceNotebook} from "./science-library";
import {Reports} from "./parent";
import {api,write,errorText} from "@/lib/client";
import type {Account,SchoolClass,Student,Group,Mission,Exercise,Progress,Control,ErrorPattern} from "@/lib/contracts";
export function TeacherSpace({account}:{account:Account}) {
  const classes=useApi<SchoolClass[]>("class/classes"),[selected,setSelected]=useState(""),[create,setCreate]=useState(false),id=selected||classes.data?.[0]?.id;
  return <><FrenchEditorial account={account}/><HistoryEditorial/><div className="title-with-action"><PageTitle eyebrow="Espace enseignant" title="À chacun sa prochaine étape.">Préparer les missions, repérer les besoins et accompagner la classe.</PageTitle>{<Button onClick={()=>setCreate(!create)}><Plus size={18}/> Créer une classe</Button>}</div>{create&&<CreateClass account={account} done={()=>{setCreate(false);classes.reload();}}/>}{classes.loading?<Loading/>:classes.error?<ErrorBox message={classes.error} retry={classes.reload}/>:!classes.data?.length?<Card><Empty title="Votre première classe vous attend."><p>{account.teacher_id?"Créez une classe pour préparer vos missions.":"Un compte enseignant doit être affecté à une classe pour commencer. L’administrateur peut réaliser cette affectation via l’API de gestion."}</p></Empty></Card>:<><div className="toolbar"><Users/><label htmlFor="class">Ma classe</label><select id="class" value={id} onChange={e=>setSelected(e.target.value)}>{classes.data.map(c=><option key={c.id} value={c.id}>{c.name} · {c.academic_year}–{c.academic_year+1}</option>)}</select></div>{id&&<ClassPanel key={id} id={id}/>}</>}</>;
}
function CreateClass({account,done}:{account:Account;done:()=>void}){const teachers=useApi<Account[]>(account.teacher_id?null:"user/accounts?limit=100");const [error,setError]=useState(""),[busy,setBusy]=useState(false);return <Card><h2>Une nouvelle classe</h2><form className="form-grid" onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);try{await write("class/classes",{name:f.get("name"),level:f.get("level"),academic_year:Number(f.get("year")),teacher_id:account.teacher_id||f.get("teacher")});done();}catch(e){setError(errorText(e));}finally{setBusy(false);}}}>{!account.teacher_id&&<label>Enseignant responsable<select name="teacher" required><option value="">Choisir un enseignant</option>{teachers.data?.filter(t=>t.teacher_id).map(t=><option key={t.id} value={t.teacher_id!}>{t.login}</option>)}</select></label>}<label>Nom<Input name="name" required maxLength={80} placeholder="Ex. CM1 des Tilleuls"/></label><label>Niveau<select name="level"><option>CM1</option><option>CM2</option></select></label><label>Année de rentrée<Input type="number" name="year" min={2020} max={2200} defaultValue={new Date().getFullYear()} required/></label><Button disabled={busy}>Créer la classe</Button>{error&&<ErrorBox message={error}/>}</form></Card>;}
function ClassPanel({id}:{id:string}) {
  const members=useApi<Student[]>(`class/classes/${id}/students`),groups=useApi<Group[]>(`class/classes/${id}/groups`),missions=useApi<Mission[]>(`class/classes/${id}/missions`),progress=useApi<Progress[]>(`analytics/classes/${id}/dashboard`),[tab,setTab]=useState("overview");
  return <><div className="tab-buttons">{[{id:"overview",label:"Vue d’ensemble"},{id:"missions",label:"Missions du jour"},{id:"groups",label:"Élèves & groupes"},{id:"science",label:"Carnets scientifiques"},{id:"controls",label:"Réglages de l’aide"}].map(t=><Button variant={tab===t.id?"default":"outline"} key={t.id} aria-pressed={tab===t.id} onClick={()=>setTab(t.id)}>{t.label}</Button>)}</div>{members.error?<ErrorBox message={members.error} retry={members.reload}/>:members.loading?<Loading/>:members.data&&<>{tab==="overview"?<div className="stack"><Card><h2>Le chemin de la classe</h2><p>Compétences observées dans la classe : un même élève peut contribuer à plusieurs compétences.</p>{progress.error?<ErrorBox message={progress.error}/>:progress.data?<ProgressBars data={progress.data.reduce((a,p)=>({competences_acquises:a.competences_acquises+p.competences_acquises,competences_en_apprentissage:a.competences_en_apprentissage+p.competences_en_apprentissage,competences_a_retravailler:a.competences_a_retravailler+p.competences_a_retravailler}),{competences_acquises:0,competences_en_apprentissage:0,competences_a_retravailler:0})}/>:<Loading/>}</Card><ClassErrors students={members.data}/><Reports/></div>:tab==="science"?<ClassScience students={members.data}/>:tab==="missions"?<div className="stack"><MissionForm classId={id} groups={groups.data||[]} done={missions.reload}/><Card><h2>Les missions préparées</h2>{missions.error?<ErrorBox message={missions.error}/>:!missions.data?.length?<p>Aucune mission pour cette classe.</p>:missions.data.map(m=><MissionRow key={m.id} mission={m} reload={missions.reload}/>)}</Card></div>:tab==="groups"?<div className="stack"><Enroll classId={id} members={members.data} reload={()=>{members.reload();groups.reload();progress.reload();}}/><GroupForm classId={id} students={members.data} groups={groups.data||[]} done={groups.reload}/></div>:<Card><h2><ShieldCheck className="inline-icon"/> Un cadre d’aide pour chaque élève</h2><p>Ces limites s’appliquent sur le serveur. Elles ne remplacent pas les accords du parent et de l’enfant.</p>{members.data.length?members.data.map(s=><ControlRow key={s.id} student={s} classId={id}/>):<p>Inscrivez d’abord les élèves dans la classe.</p>}</Card>}</>}</>;
}
function ClassErrors({students}:{students:Student[]}) {const [patterns,setPatterns]=useState<ErrorPattern[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true);useEffect(()=>{let alive=true;Promise.all(students.map(s=>api<ErrorPattern[]>(`assessment/students/${s.id}/errors`))).then(all=>{if(alive)setPatterns(all.flat().filter(x=>x.recurring));}).catch(e=>{if(alive)setError(errorText(e));}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[students]);const grouped=Array.from(new Map(patterns.map(p=>[p.error_code,p])).values());return <Card><h2>Ce qui mérite un nouvel éclairage</h2><p>Types de difficultés récurrentes observées, sans classement des élèves.</p>{loading?<Loading/>:error?<ErrorBox message={error}/>:!grouped.length?<p>Aucun schéma récurrent signalé pour le moment.</p>:<ul className="objectives">{grouped.map(p=><li key={p.error_code}>{p.message}</li>)}</ul>}</Card>;}
function MissionForm({classId,groups,done}:{classId:string;groups:Group[];done:()=>void}){const exercises=useApi<Exercise[]>("exercise/exercises?limit=100"),[selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");return <Card><h2><Compass className="inline-icon"/> Composer une mission</h2><p>Choisissez des exercices validés. Deux exercices ou plus permettent de distinguer entraînement guidé et autonomie.</p><form className="stack" onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);try{await write(`class/classes/${classId}/missions`,{title:f.get("title"),day:f.get("day"),group_id:f.get("group")||null,exercise_version_ids:selected});setNotice("Mission publiée pour les élèves concernés.");done();}catch(e){setError(errorText(e));}finally{setBusy(false);}}}><div className="form-grid"><label>Titre de la mission<Input name="title" required maxLength={160} placeholder="Ex. Des fractions dans ma cuisine"/></label><label>Jour<input type="date" name="day" required defaultValue={new Date().toLocaleDateString("en-CA")}/></label><label>Destinataires<select name="group"><option value="">Toute la classe</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label></div><fieldset><legend>Exercices publiés · {selected.length} sélectionné(s)</legend>{exercises.loading?<Loading/>:exercises.error?<ErrorBox message={exercises.error}/>:!exercises.data?.length?<p>Aucun exercice publié. Un contenu doit être créé et validé par l’équipe pédagogique avant de composer une mission.</p>:<div className="exercise-picker">{exercises.data.map(e=><label key={e.id} className="checkbox-label"><input type="checkbox" checked={selected.includes(e.id)} disabled={!selected.includes(e.id)&&selected.length>=12} onChange={event=>setSelected(ids=>event.target.checked?[...ids,e.id]:ids.filter(x=>x!==e.id))}/><span>{e.prompt.instruction}<small>{e.prompt.parts.length} question(s) · {({multiple_choice:"QCM",fill_blanks:"Texte à compléter",short_text:"Réponse courte",step_problem:"Problème à étapes",ordering:"Classement",timeline:"Frise chronologique"} as Record<string,string>)[e.kind]||"Exercice"}</small></span></label>)}</div>}</fieldset><Button disabled={busy||!selected.length}>Publier la mission</Button><p role="status">{notice}</p>{error&&<ErrorBox message={error}/>}</form></Card>;}
function MissionRow({mission,reload}:{mission:Mission;reload:()=>void}) {const [error,setError]=useState("");return <article className="list-row"><div><h3>{mission.title}</h3><p>{new Date(mission.day+"T12:00:00").toLocaleDateString("fr-FR")} · {mission.exercise_version_ids.length} activités · {mission.status==="archived"?"Archivée":"Publiée"}</p></div>{mission.status!=="archived"&&<Button variant="outline" onClick={async()=>{try{await write(`class/classes/${mission.class_id}/missions/${mission.id}/archive`,{});reload();}catch(e){setError(errorText(e));}}}>Archiver</Button>}{error&&<ErrorBox message={error}/>}</article>;}
function GroupForm({classId,students,groups,done}:{classId:string;students:Student[];groups:Group[];done:()=>void}){const [editing,setEditing]=useState(""),[name,setName]=useState(""),[selected,setSelected]=useState<string[]>([]),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);return <Card><h2>Des groupes selon les besoins</h2><div className="toolbar"><label htmlFor="edit-group">Groupe</label><select id="edit-group" value={editing} onChange={e=>{setEditing(e.target.value);const g=groups.find(g=>g.id===e.target.value);setName(g?.name||"");setSelected(g?.student_ids||[]);}}><option value="">Nouveau groupe</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></div><form className="stack" onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");try{await write(`class/classes/${classId}/groups${editing?`/${editing}`:""}`,{name,student_ids:selected},editing?"PUT":"POST");setNotice("Groupe enregistré.");done();}catch(e){setError(errorText(e));}finally{setBusy(false);}}}><label>Nom du groupe<Input value={name} onChange={e=>setName(e.target.value)} required maxLength={80} placeholder="Ex. Atelier des explorateurs"/></label><fieldset><legend>Élèves du groupe</legend><div className="checkbox-grid">{students.map(s=><label className="checkbox-label" key={s.id}><input type="checkbox" checked={selected.includes(s.id)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,s.id]:ids.filter(id=>id!==s.id))}/>{s.pseudonym}</label>)}</div></fieldset><Button disabled={busy||!selected.length}>Enregistrer le groupe</Button><p role="status">{notice}</p>{error&&<ErrorBox message={error}/>}</form></Card>;}
function Enroll({classId,members,reload}:{classId:string;members:Student[];reload:()=>void}){const students=useApi<Student[]>("user/students?limit=100"),[error,setError]=useState(""),[busy,setBusy]=useState(false);return <Card><h2>Élèves de la classe</h2><ul className="history-list">{members.map(s=><li key={s.id}><span>{s.pseudonym}</span><Button variant="ghost" onClick={async()=>{if(!window.confirm(`Retirer ${s.pseudonym} de cette classe ?`))return;try{await api(`class/classes/${classId}/students/${s.id}`,{method:"DELETE"});reload();}catch(e){setError(errorText(e));}}}>Retirer de la classe</Button></li>)}</ul><form className="toolbar" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await write(`class/classes/${classId}/students`,{student_id:f.get("student")});reload();}catch(e){setError(errorText(e));}finally{setBusy(false);}}}><label htmlFor="enroll-student">Ajouter un élève autorisé</label><select required id="enroll-student" name="student"><option value="">Choisir un élève</option>{students.data?.filter(s=>!members.some(m=>m.id===s.id)).map(s=><option value={s.id} key={s.id}>{s.pseudonym} · {s.level}</option>)}</select><Button disabled={busy}>Inscrire</Button></form><p className="hint-text">Pour un nouvel élève hors de votre périmètre, demandez son affectation à l’administrateur.</p>{error&&<ErrorBox message={error}/>}</Card>;}
function ControlRow({student,classId}:{student:Student;classId:string}){const path=`class/classes/${classId}/students/${student.id}/tutor-control`,control=useApi<Control>(path),[enabled,setEnabled]=useState<boolean|null>(null),[limit,setLimit]=useState<number|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);return <form className="control-row" onSubmit={async e=>{e.preventDefault();if(!control.data)return;setBusy(true);setError("");try{await write(path,{enabled:enabled??control.data.enabled,max_help:limit??control.data.max_help,expected_revision:control.data.revision},"PUT");control.reload();setNotice("Réglage appliqué.");}catch(e){setError(errorText(e));control.reload();}finally{setBusy(false);}}}><h3>{student.pseudonym}</h3>{control.error?<ErrorBox message={control.error}/>:control.data?<><label className="checkbox-label"><input type="checkbox" checked={enabled??control.data.enabled} onChange={e=>setEnabled(e.target.checked)}/> Accompagnement IA autorisé</label><label>Niveau d’aide maximal<select value={limit??control.data.max_help} onChange={e=>setLimit(Number(e.target.value))}>{[0,1,2,3,4,5,6].map(n=><option key={n} value={n}>{n} · {n===0?"Questionnement":n===6?"Méthode partielle":"Indice progressif"}</option>)}</select></label><Button disabled={busy}>Appliquer</Button></>:<Loading/>}<p role="status">{notice}</p>{error&&<ErrorBox message={error}/>}</form>;}

function ClassScience({students}:{students:Student[]}){const [chosen,setChosen]=useState("");const id=chosen||students[0]?.id;return <><label htmlFor="science-student">Carnet de l’élève</label><select id="science-student" value={id??""} onChange={e=>setChosen(e.target.value)}>{students.map(s=><option key={s.id} value={s.id}>{s.pseudonym}</option>)}</select>{id?<ScienceNotebook key={id} studentId={id} readOnly/>:<p>Aucun élève dans cette classe.</p>}</>;}
