"""Additional original CM2 workshops. Public reading passages contain no answers."""

def ordered(question,labels,steps):
    # Deliberately shuffled display; expected order stays private.
    options=[{"id":f"s{i}","label":label} for i,label in enumerate(labels)]
    return {"question":question,"response_type":"ordering","options":options[1:]+options[:1],
        "rule":{"mode":"ordering","expected":[o["id"] for o in options],"solution_steps":steps}}


def build_courses(lesson,text,choice):
    return [
    lesson("CIRCONSTANCES","Explorer le lieu, le temps et la cause","Identifier des compléments circonstanciels de lieu de temps et de cause",
        "« Ce matin, Maya lit dans le jardin. » Imagine la scène : les petits groupes précisent le moment et le lieu.",
        "Un complément circonstanciel précise les circonstances : quand, où ou pourquoi. Dans les phrases de cet atelier, on peut le déplacer ou le supprimer en gardant une phrase construite. Cela aide à le distinguer d'un complément du verbe.",
        ["« Hier, Paul dessinait dans sa chambre. » Hier indique le temps ; dans sa chambre indique le lieu.","Je déplace : Dans sa chambre, Paul dessinait hier. Je supprime : Paul dessinait."],
        [choice("« Le soir, Lila raconte une histoire. » Quel groupe indique le moment ?",["Le soir","Lila","une histoire"],0,["Le soir précise quand Lila raconte. C'est un complément circonstanciel de temps."]),
         choice("« Les enfants jouent sous le préau. » Que précise sous le préau ?",["Le temps","Le lieu","La cause"],1,["Sous le préau indique où les enfants jouent : le lieu."]),
         choice("« À cause de la pluie, le match est annulé. » Que précise À cause de la pluie ?",["Le lieu","La cause","Le sujet"],1,["Le groupe explique pourquoi le match est annulé. Il exprime la cause."])],
        ["Cherche ce qui situe la scène.","Essaie de déplacer le groupe : précise-t-il quand, où ou pourquoi ?"]),
    lesson("PRONOMS","Suivre les personnages grâce aux pronoms","Identifier le nom ou le groupe repris par un pronom",
        "« Zoé ouvre un livre. Elle lit la première page. » Comment sait-on qui lit ?",
        "Un pronom peut reprendre un nom ou un groupe déjà cité. Il évite des répétitions. Pour comprendre qui il désigne, vérifie le sens et les mots du texte. Si plusieurs personnes sont possibles, réécris le nom pour être clair.",
        ["« Les oiseaux s'envolent. Ils passent au-dessus du toit. » Ils reprend les oiseaux.","Ils est un pronom personnel, masculin pluriel. Dans la deuxième phrase, il est sujet de passent."],
        [choice("« Léa pose son sac. Elle entre en classe. » Qui est Elle ?",["Léa","Le sac","La classe"],0,["Elle reprend Léa. Le sac ne peut pas entrer en classe de lui-même dans cette scène."]),
         choice("« Tom rencontre ses cousins. Ils portent tous un manteau rouge. » Pourquoi la reprise peut-elle manquer de précision ?",["On ne sait pas si Tom est inclus dans ils","Ils désigne forcément le manteau","Il manque un verbe"],0,["Ils peut désigner les cousins seuls ou Tom avec ses cousins. Un nom précis enlèverait le doute."]),
         text("Réécris en remplaçant seulement la répétition : Les filles arrivent. Les filles sourient.","Les filles arrivent. Elles sourient.",["Elles reprend les filles, féminin pluriel. Elles est sujet de sourient."],variants=["Les filles arrivent. Elles sourient"])],
        ["Remonte dans la phrase précédente.","Vérifie le nombre et le genre, puis vérifie que le sens convient."]),
    lesson("EXPANSIONS","Enrichir un groupe nominal","Distinguer adjectif épithète et complément du nom",
        "Une annonce indique « un sac ». « Un sac bleu » ou « un sac de sport » aide à le reconnaître.",
        "Le nom est le centre du groupe nominal. On peut le préciser avec un adjectif épithète, placé auprès du nom, ou avec un complément du nom, souvent introduit par une préposition comme de ou à. Épithète et complément du nom sont des fonctions.",
        ["Dans un petit jardin, petit est un adjectif épithète du nom jardin.","Dans un jardin de roses, de roses est complément du nom jardin."],
        [choice("Dans « une veste rouge », quel mot précise le nom veste ?",["une","rouge","veste"],1,["Rouge est un adjectif épithète du nom veste. Il indique une couleur."]),
         choice("Dans « un bateau à voiles », quelle est la fonction de à voiles ?",["Sujet","Complément du nom bateau","Verbe"],1,["À voiles précise le nom bateau et non un verbe. C'est son complément du nom."]),
         text("Enrichis « un chemin » avec un adjectif et un complément du nom.","un petit chemin de campagne",["Petit est un adjectif épithète ; de campagne est complément du nom chemin.","D'autres groupes sont possibles : vérifie que tu as bien ajouté les deux précisions."],mode="open_writing")],
        ["Repère le nom principal du groupe.","Observe la précision : un adjectif seul, ou un groupe introduit par de ou à ?"]),
    lesson("PARTICIPE-ETRE","Accorder le participe passé avec être","Accorder un participe passé avec le sujet dans les cas simples avec être",
        "Tu racontes l'arrivée de tes amies : « Elles sont arrivées. » La fin du participe passé donne un indice sur le sujet.",
        "Dans les exemples simples de cet atelier, le passé composé utilise être au présent et un participe passé. Le participe passé s'accorde avec le sujet en genre et en nombre. Un participe passé est une forme du verbe, comme arrivé. Les verbes pronominaux, comme se laver, ne sont pas étudiés ici.",
        ["Lina est arrivée : Lina est féminin singulier, donc arrivée prend e.","Lina et Zoé sont arrivées : le sujet est féminin pluriel, donc arrivées prend es."],
        [text("Complète avec arrivé : Nora est … .","arrivée",["Le sujet Nora est féminin singulier. Avec être, arrivé s'accorde ici : arrivée."],known_errors={"arrivé":"AGREEMENT_ERROR"}),
         text("Complète avec parti : Les garçons sont … .","partis",["Les garçons est masculin pluriel. Le participe passé avec être prend s : partis."],known_errors={"parti":"AGREEMENT_ERROR"}),
         text("Complète avec tombé : Les feuilles sont … .","tombées",["Le sujet les feuilles est féminin pluriel. Le participe passé tombées prend e et s."],known_errors={"tombé":"AGREEMENT_ERROR","tombés":"AGREEMENT_ERROR","tombée":"AGREEMENT_ERROR"})],
        ["Repère l'auxiliaire être, puis le sujet.","Le sujet est-il féminin ou masculin, singulier ou pluriel ?"]),
    lesson("ON-ONT","Choisir entre on et ont","Distinguer le pronom on du verbe avoir ont",
        "« On prépare le goûter. Les enfants ont faim. » Même son, mais deux rôles différents.",
        "On est un pronom sujet : on peut le remplacer par il. Ont est le verbe avoir au présent, avec ils ou elles : on peut le remplacer par avaient. Teste le remplacement dans toute la phrase.",
        ["On joue devient il joue : j'écris on.","Elles ont froid devient elles avaient froid : j'écris ont."],
        [text("Complète par on ou ont : … entend les oiseaux.","on",["Il entend les oiseaux est possible. On est le pronom sujet."],known_errors={"ont":"CONJUGATION_ERROR"}),
         text("Complète par on ou ont : Les élèves … leurs cahiers.","ont",["Les élèves avaient leurs cahiers est possible. Ont est avoir au présent."],known_errors={"on":"CONJUGATION_ERROR"}),
         text("Complète par on ou ont : Elles … terminé la lecture.","ont",["Elles avaient terminé est possible. Ont est l'auxiliaire avoir au présent dans ont terminé."],known_errors={"on":"CONJUGATION_ERROR"})],
        ["Essaie il à la place du mot manquant.","Essaie ensuite avaient. Quel remplacement conserve une phrase construite ?"]),
    lesson("SYNONYMES","Choisir un mot de sens proche","Choisir un synonyme adapté au contexte",
        "Dans un récit, ton personnage est « content ». Tu peux parfois écrire « joyeux » pour préciser son émotion.",
        "Des synonymes sont des mots de sens proche. Ils ne se remplacent pas dans toutes les phrases : relis le contexte. Un synonyme doit garder le sens voulu et convenir à la construction de la phrase.",
        ["« Un exercice difficile » peut devenir « un exercice compliqué ».","Dans « un vent fort », puissant convient mieux que courageux, même si un personnage fort peut être courageux."],
        [choice("Dans « une maison immense », quel mot peut remplacer immense ?",["Minuscule","Très grande","Ancienne"],1,["Immense signifie très grande. Ancienne parle de l'âge, pas de la taille."]),
         choice("« Il chuchote pour ne pas réveiller le bébé. » Quel sens convient à chuchote ?",["Parle très fort","Parle à voix basse","Court vite"],1,["Le but est de ne pas réveiller le bébé. Chuchoter signifie parler à voix basse."]),
         text("Réécris « Lina est contente de retrouver son amie » en remplaçant contente par un mot de sens proche.","Lina est heureuse de retrouver son amie.",["Heureuse garde ici le sens de contente. Joyeuse convient aussi.","Vérifie l'accord au féminin et que ton choix garde le sens de la phrase."],mode="open_writing")],
        ["Observe ce que le mot décrit : taille, émotion, manière d'agir…","Relis la phrase avec le mot proposé et vérifie qu'elle garde son sens."]),
    lesson("ANTONYMES","Exprimer le contraire avec précision","Trouver un antonyme adapté au sens d'un mot",
        "Sur une porte, tu lis ouvert. De l'autre côté, le panneau indique fermé.",
        "Des antonymes sont des mots de sens contraire. Le contraire dépend du contexte. Certains se forment avec un préfixe, une partie ajoutée au début : possible devient impossible. On ne peut pas ajouter im- à tous les mots.",
        ["Le contraire de lourd est léger quand on parle de masse.","Dans un problème facile, le contraire de facile est difficile."],
        [choice("Quel est le contraire de silencieux dans « un lieu silencieux » ?",["Calme","Bruyant","Lointain"],1,["Bruyant exprime le contraire de silencieux. Lointain indique une distance."]),
         choice("« Cette réponse est exacte. » Quel mot exprime le contraire d'exacte ?",["Inexacte","Précise","Courte"],0,["Inexacte signifie qui n'est pas exacte. In- est ajouté au début du mot."]),
         text("Dans « une valise pleine », écris seulement le contraire de pleine.","vide",["Une valise pleine contient des objets. Une valise vide n'en contient pas."],mode="spelling")],
        ["Cherche le sens du mot dans cette phrase.","Imagine la situation opposée ; ne change pas de sujet."]),
    lesson("DICTIONNAIRE","Chercher un mot dans le dictionnaire","Utiliser l'ordre alphabétique et choisir le sens d'une définition",
        "Tu cherches le mot canal dans un dictionnaire. Regarder seulement la première lettre ne suffit pas.",
        "Le dictionnaire range les mots dans l'ordre alphabétique. Compare la première lettre différente. Un article peut donner la classe du mot et plusieurs sens. Choisis la définition qui convient à la phrase.",
        ["Carte vient avant chat : les deux commencent par c, puis a vient avant h.","Dans « le canal transporte de l'eau », canal désigne une voie d'eau, pas une chaîne de télévision."],
        [choice("Quel mot vient en premier dans le dictionnaire ?",["lapin","arbre","bateau"],1,["A vient avant b et l. Arbre est le premier."]),
         ordered("Range ces trois mots dans l'ordre du dictionnaire.",["cahier","canal","carte"],["Les trois mots commencent par ca. Compare ensuite h, n et r : h vient avant n, puis r."]),
         choice("Article : « banc, nom masculin : 1. siège long ; 2. groupe de poissons ». Dans « un banc de sardines », quel sens choisis-tu ?",["Le siège long","Le groupe de poissons"],1,["Sardines indique des poissons. Il faut choisir le deuxième sens."])],
        ["Compare les lettres de gauche à droite.","À la première différence, utilise l'ordre de l'alphabet. Pour un sens, relis la phrase."]),
    lesson("LECTURE-ENQUETE","Mener une petite enquête de lecture","Prélever et relier des informations explicites dans un récit",
        "À la bibliothèque, un personnage cherche un livre perdu. Pour l'aider, il faut lire les indices dans le bon ordre.",
        "Une information explicite est écrite dans le texte. Pour la retrouver, repère les personnages, les lieux et les actions. Relis la phrase qui prouve ta réponse. L'ordre des actions aide à comprendre le récit.",
        ["« À midi, Noé pose son livre sur le banc. Il part chercher de l'eau. » Le livre est sur le banc.","Je peux citer la première phrase pour justifier cette information."],
        [choice("« Ada entre dans la bibliothèque. Elle pose son sac près de la fenêtre, puis cherche un conte. » Où pose-t-elle son sac ?",["Sous la table","Près de la fenêtre","À la porte"],1,["Le texte indique exactement près de la fenêtre. Il faut reprendre cette information."]),
         ordered("Texte : « Ada trouve un livre. Elle le fait enregistrer, puis le range dans son sac. » Replace les actions dans l'ordre du récit.",["Ada trouve un livre.","Elle le fait enregistrer.","Elle le range dans son sac."],["L'ordre est donné par le récit. Trouver vient d'abord, enregistrer ensuite, ranger enfin."]),
         text("« Au retour, Ada ne retrouve plus sa carte. Elle vide la petite poche de son sac : la carte y était restée. » Où retrouve-t-elle sa carte ? Justifie avec le texte.","Dans la petite poche de son sac : la carte y était restée.",["La carte est dans la petite poche. Y reprend cet endroit.","Ta réponse doit relier la carte et la poche en s'appuyant sur les deux dernières phrases."],mode="open_writing")],
        ["Relis le passage qui parle de l'objet recherché.","Repère le groupe qui précise le lieu ou le mot qui indique l'ordre des actions."]),
    lesson("RESUMER","Garder l'essentiel d'une histoire","Résumer un récit en gardant les événements importants",
        "Tu racontes un livre à un ami. Tu n'as pas besoin de répéter toutes les phrases pour qu'il comprenne l'histoire.",
        "Un résumé garde les personnages et les événements indispensables. Il respecte l'ordre et n'ajoute pas d'aventure inventée. Les petits détails peuvent être retirés s'ils ne changent pas la compréhension.",
        ["Récit : Nina perd son bonnet rouge en allant au parc. Un voisin le trouve et le lui rend.","Résumé : Nina perd son bonnet, puis un voisin le retrouve et le lui rend. La couleur n'est pas indispensable ici."],
        [choice("« Tom oublie son goûter. Son amie lui offre une pomme. » Quelle information faut-il garder pour comprendre l'aide de son amie ?",["Tom a oublié son goûter","La pomme est dans un joli sac","Tom aime les vélos"],0,["L'oubli explique pourquoi son amie l'aide. Les autres détails ne sont pas donnés."]),
         text("Résume en une phrase : « Une tortue tombe dans un trou peu profond. Un enfant apporte une planche. La tortue grimpe sur la planche et sort. »","Un enfant aide une tortue à sortir d'un trou avec une planche.",["Ce résumé garde la difficulté, l'aide et la sortie.","Compare ta phrase : elle doit garder ces événements sans en inventer d'autres."],mode="open_writing"),
         text("Résume en deux phrases : « La classe prépare une exposition sur les arbres. Les élèves dessinent les feuilles et écrivent des légendes. Le vendredi, ils montrent leurs affiches aux familles. »","La classe prépare des affiches sur les arbres avec des dessins et des légendes. Les élèves les présentent aux familles le vendredi.",["Le résumé garde le projet, le travail réalisé et sa présentation.","Une autre formulation est possible. Vérifie l'ordre des actions et la fidélité au récit."],mode="open_writing")],
        ["Repère ce qui arrive au personnage ou ce que le groupe réalise.","Garde le problème, l'action et la fin. Retire un détail seulement si l'histoire reste compréhensible."]),
    ]
