"""Enriched teaching bodies (v2) for the 28 French CM2 workshops.

The exercises, answers and objectives stay exactly those of the staged v1 pack.
Only the lesson fields below change: prerequisites, discovery, explanation,
method, worked_example and common_errors. Discovery and explanation accept
several paragraphs separated by \n; the web reader renders one <p> per line.
"""
from copy import deepcopy

from .french_pack import COURSES

DEEPENINGS = {
 "CM2-FR-NATURES": {
  "prerequisites": ["Reconnaître un nom, un verbe, un adjectif et un déterminant.",
   "Trouver le verbe conjugué dans une phrase."],
  "discovery": "Deux étiquettes sont accrochées au tableau : sur la première, « nom » ; sur la seconde, « sujet ».\nUn élève place le mot chat sous la première, puis le groupe le chat sous la seconde. Pourquoi deux mots différents sur les étiquettes ? Tout simplement parce qu'on ne pose pas la même question : quel genre de mot est chat ? Quel rôle joue le chat dans cette phrase ?",
  "explanation": "La classe d'un mot est sa catégorie : nom, verbe, adjectif, déterminant, pronom, adverbe… C'est ce que dit le dictionnaire, et cela ne change jamais. Le mot chat est un nom dans toutes les phrases du monde ; dort est toujours un verbe.\nLa fonction d'un mot ou d'un groupe est son rôle dans une phrase précise : sujet du verbe, complément d'objet direct, attribut… Cela peut changer d'une phrase à l'autre. Dans « Le chat dort », le groupe le chat est sujet. Dans « Je caresse le chat », ce même groupe devient complément d'objet direct du verbe caresse.\nPour ne pas les confondre, pose-toi deux questions différentes. Classe : « quel genre de mot ? » — que désigne-t-il, que fait-il ? Fonction : « quel travail fait-il ici ? » — repère le verbe conjugué, puis cherche le groupe qui commande son accord. Un même mot garde sa classe mais peut changer de fonction ; une fonction ne se dit que d'un groupe dans une phrase.",
  "method": ["Lis bien la question : demande-t-elle une catégorie de mot (la classe) ou un rôle dans la phrase (la fonction) ?",
   "Pour la classe, demande-toi : ce mot désigne-t-il (nom), fait-il une action (verbe), décrit-il (adjectif), annonce-t-il (déterminant) ?",
   "Pour la fonction, repère d'abord le verbe conjugué.",
   "Teste avec un remplacement ou un déplacement : le groupe qui commande l'accord du verbe est le sujet.",
   "Réponds en nommant les deux quand c'est possible : « chat est un nom (classe) ; le chat est sujet (fonction) »."],
  "worked_example": ["« Nina observe le papillon. » — Classe : papillon est un nom, observe est un verbe, le est un déterminant. Fonction : le groupe Nina est sujet du verbe observe ; le groupe le papillon complète directement observe, c'est le complément d'objet direct.",
   "« Le papillon s'envole. » — Papillon est toujours un nom (sa classe n'a pas changé), mais cette fois le groupe le papillon est devenu le sujet du verbe s'envole.",
   "« Le papillon bleu vole. » — Bleu est un adjectif : c'est sa classe. Dans cette phrase, il est épithète du nom papillon : c'est sa fonction."],
  "common_errors": ["Écrire que chat est un « sujet » : sujet est une fonction ; la classe de chat est nom. On dit : le groupe le chat est sujet.",
   "Croire qu'un mot garde la même fonction partout : dans « Le chat dort » le chat est sujet ; dans « Je dessine le chat » il devient COD.",
   "Confondre le mot seul et le groupe : c'est le groupe entier « le chat » qui est sujet, pas seulement le mot chat."]},

 "CM2-FR-FONCTIONS": {
  "prerequisites": ["Trouver le verbe conjugué d'une phrase.",
   "Remplacer un groupe par il, elle, ils ou elles."],
  "discovery": "« Au loin arrivent deux bateaux. » La phrase semble bizarre : le verbe arrive avant!\nPourtant, tout se passe comme dans une phrase ordinaire : il y a un sujet, et c'est lui qui commande la terminaison du verbe. Il faut simplement apprendre à le chercher même quand il n'est pas au début.",
  "explanation": "Le sujet est le groupe qui commande l'accord du verbe : on le retrouve avec la question « qui est-ce qui + verbe ? ». Qui est-ce qui arrivent ? Ce sont deux bateaux : le sujet est deux bateaux, et c'est parce qu'il est pluriel que le verbe prend la terminaison -ent.\nLe sujet n'est pas toujours placé au début de la phrase. Dans les récits, on rencontre souvent « Au loin arrivent deux bateaux » ou « Sous le toit nichent des oiseaux » : un complément occupe le début, le verbe vient ensuite, et le sujet suit le verbe. La place ne change rien au rôle : c'est toujours le groupe qui commande l'accord.\nDeux tests fiables : remplace le groupe trouvé par un pronom (ils arrivent au loin) ; ou déplace le groupe au début de la phrase (Deux bateaux arrivent au loin). Si la phrase reste construite et l'accord correct, tu as trouvé le sujet.",
  "method": ["Repère le verbe conjugué : c'est le mot qui change si on change le temps (hier, demain…).",
   "Pose la question « qui est-ce qui + verbe ? » et cherche la réponse, même après le verbe.",
   "Remplace le groupe trouvé par il/elle ou ils/elles pour vérifier son nombre.",
   "Accorde le verbe avec ce sujet, jamais avec le mot placé juste avant lui.",
   "En cas de doute, réécris la phrase avec le sujet en tête : l'accord doit rester le même."],
  "worked_example": ["« Sur la place jouent les enfants. » Le verbe est jouent. Qui est-ce qui jouent ? Les enfants. Test : ils jouent sur la place. Le sujet les enfants suit le verbe, et c'est lui qui explique le -ent de jouent.",
   "« Près du mur poussent des fleurs. » Qui est-ce qui poussent ? Des fleurs : elles poussent près du mur. Le sujet des fleurs arrive après le verbe poussent ; murs est singulier, mais ce n'est pas lui qui commande.",
   "« Au loin arrivent deux bateaux. » On peut écrire : Deux bateaux arrivent au loin. La phrase déplacée montre bien le sujet deux bateaux, pluriel, d'où arrivent."],
  "common_errors": ["Accorder le verbe avec le mot qui le précède : dans « Sous le toit nichent des oiseaux », le verbe s'accorde avec des oiseaux (pluriel), pas avec toit (singulier).",
   "Croire que le sujet est toujours le premier groupe de la phrase : ici, « sous le toit » indique le lieu, ce n'est pas le sujet.",
   "Oublier de vérifier avec le remplacement par ils/elles : c'est le test le plus rapide pour choisir la terminaison."]},

 "CM2-FR-OBJETS": {
  "prerequisites": ["Trouver le verbe conjugué et son sujet.",
   "Connaître les prépositions à, de, en, dans."],
  "discovery": "« Lina regarde un film. » « Lina parle de ce film. » Deux phrases, un même mot, film.\nPourtant, le verbe ne se construit pas de la même façon : dans la première, on regarde quelque chose ; dans la seconde, on parle de quelque chose. Cette petite différence change la fonction du complément.",
  "explanation": "Le complément d'objet complète le verbe : il dit ce que le sujet fait, regarde, lit… On le trouve avec les questions « quoi ? » ou « qui ? » posées après le verbe. Il y en a deux sortes à distinguer au CM2.\nLe complément d'objet direct (COD) suit le verbe sans préposition : regarder quoi ? un film. On peut le remplacer par le, la, l' ou les : Lina le regarde. Le complément d'objet indirect (COI) est relié au verbe par une préposition, le plus souvent à ou de : parler de quoi ? de ce film. On le remplace par lui ou leur : Lina en parle / Lina lui parle.\nAttention, la préposition ne suffit pas à elle seule : un complément de lieu (« aller à Paris ») commence aussi par à, mais il ne complète pas le verbe de la même façon. Vérifie toujours le lien avec le verbe : est-ce que le complément complète l'action (lire, parler, penser…) ou situe-t-il autrement l'action ? Remplacer par un pronom (le/la/les contre lui/leur) est le test le plus sûr.",
  "method": ["Repère le verbe conjugué, puis son sujet.",
   "Pose la question « verbe + quoi ? » ou « verbe + qui ? » pour trouver le complément d'objet.",
   "Regarde s'il y a une préposition (à, de…) entre le verbe et ce complément.",
   "Sans préposition : c'est un COD. Avec à ou de : c'est un COI.",
   "Confirme par un remplacement : le/la/les pour un COD ; lui/leur (ou en/y) pour un COI."],
  "worked_example": ["« Je lis un livre. » Question : je lis quoi ? un livre, sans préposition. Test : je le lis. Un livre est COD du verbe lis.",
   "« Tu penses à ton ami. » Question : tu penses à qui ? à ton ami, avec la préposition à. Test : tu penses à lui. À ton ami est COI du verbe penses.",
   "« Elle parle de son voyage. » Parler de quoi ? de son voyage, introduit par de : c'est un COI. Compare : « Elle prépare son voyage » — là, son voyage serait un COD, car préparer se construit sans préposition."],
  "common_errors": ["Appeler COD tout groupe placé après le verbe : « à ton ami » n'est pas un COD, la préposition à en fait un COI.",
   "Décider uniquement avec la préposition sans vérifier le sens : dans « Je vais à Paris », à introduit un lieu, pas un complément d'objet du verbe vais.",
   "Oublier que certains verbes se construisent toujours avec une préposition : penser à, parler à ou de, rêver de — leur complément est indirect."]},

 "CM2-FR-ACCORDS": {
  "prerequisites": ["Repérer le nom noyau d'un groupe nominal.",
   "Distinguer masculin/féminin et singulier/pluriel."],
  "discovery": "Dans la vitrine d'une fleuriste : « une petite fleur ». Le lendemain, l'annonce est changée : « des petites fleurs ».\nTrois mots ont changé ensemble : une est devenu des, petite est devenu petites, fleur est devenu fleurs. Le nom a entraîné tout son groupe dans le changement : c'est la chaîne des accords.",
  "explanation": "Dans le groupe nominal (déterminant + nom + adjectif), le nom est le chef : il donne son genre (masculin ou féminin) et son nombre (singulier ou pluriel) aux autres mots du groupe. Le déterminant et l'adjectif s'accordent avec lui.\nLa méthode est toujours la même : regarde d'abord le nom seul. Est-il masculin ou féminin ? Une seule chose ou plusieurs ? Puis transmets l'information : au déterminant, puis à l'adjectif. Dans les cas réguliers, on ajoute e au féminin et s au pluriel : un petit arbre, une petite fleur, des petits arbres, des petites fleurs.\nBeaucoup d'accords sont réguliers, mais la langue garde des formes particulières : beau/belle, un vieil homme, des animaux joyeux sans e car joyeux se termine par un x. Quand tu hésites sur l'adjectif, essaie de le dire au féminin à voix haute : la couleur te guide souvent (vert/verte, long/longue). Et n'oublie pas : c'est le nom, jamais le déterminant ni le mot d'à côté, qui décide de l'accord.",
  "method": ["Repère le nom noyau du groupe : c'est lui que l'adjectif et le déterminant accompagnent vraiment.",
   "Note son genre : masculin ou féminin ?",
   "Note son nombre : une seule chose ou plusieurs ?",
   "Accorde le déterminant, puis l'adjectif, en partant de ce nom (e pour le féminin, s pour le pluriel dans les cas réguliers).",
   "Relis le groupe entier d'un trait : « des petites fleurs » doit sonner juste."],
  "worked_example": ["Compléter avec petit : des … maisons. Le nom maisons est féminin pluriel → petit prend e puis s : des petites maisons.",
   "Mettre au pluriel « un grand arbre » : arbre devient arbres (masculin pluriel), grand prend s, et un devient des : des grands arbres.",
   "Compléter avec vert : les feuilles … . Feuilles est féminin pluriel, et vert prend un e au féminin : les feuilles vertes. Au masculin pluriel on écrirait les arbres verts."],
  "common_errors": ["Accorder l'adjectif avec le déterminant au lieu du nom : dans « la petite fleur », c'est fleur (féminin) qui commande, et la est simplement le déterminant.",
   "Oublier le s du pluriel sur l'adjectif : « des petites fleur » est faux sur deux mots (fleurs et petites).",
   "Mettre un e à tous les adjectifs pluriels : « des arbres vertes » est faux ; arbres est masculin, on écrit verts."]},

 "CM2-FR-ATTRIBUT": {
  "prerequisites": ["Repérer le sujet d'un verbe.",
   "Accorder un adjectif dans le groupe nominal."],
  "discovery": "« Les filles sont fatiguées. » « Les routes sont longues. »\nIci, l'adjectif n'est pas collé à un nom comme dans « une longue route ». Il est relié au sujet par un verbe : il dit comment est le sujet. Ce pont entre le sujet et l'adjectif s'appelle le verbe d'état, et l'adjectif joue un rôle bien précis : attribut du sujet.",
  "explanation": "Un adjectif peut décrire un nom de deux façons. Collé au nom, sans verbe entre eux, il est épithète : « une route longue ». Relié au sujet par un verbe d'état comme être, sembler, devenir, paraître, il est attribut du sujet : « la route est longue ». L'attribut dit ce qu'est le sujet, comment il semble ou ce qu'il devient.\nL'attribut s'accorde toujours avec le sujet, jamais avec le verbe ni avec un autre mot de la phrase. Dans « Les filles sont fatiguées », le sujet les filles est féminin pluriel : fatiguées prend e et s. Un test utile : l'attribut est indispensable — « Les routes sont » tout seul ne veut rien dire ; alors qu'un complément comme « dans la ville » peut être retiré.\nAttention au piège du COD : après être, on ne trouve pas de COD. « Les filles regardent un film » : un film est COD de regardent. « Les filles sont fatiguées » : fatiguees est attribut du sujet les filles. La présence d'un verbe d'état (être, sembler, devenir, paraître) est le signal de l'attribut.",
  "method": ["Repère le verbe : est-ce un verbe d'état (être, sembler, devenir, paraître) ou un verbe d'action ?",
   "Cherche le mot ou le groupe qui dit comment est le sujet : c'est l'attribut.",
   "Remplace le sujet par il, elle, ils ou elles pour connaître son genre et son nombre.",
   "Accorde l'adjectif attribut avec ce sujet : e pour le féminin, s pour le pluriel (cas réguliers).",
   "Vérifie le sens : l'attribut peut être enlevé seulement si la phrase reste complète — sinon, il est indispensable."],
  "worked_example": ["« Le chat est calme. » Calme est un adjectif relié au sujet le chat par le verbe est : sa fonction est attribut du sujet. Chat est masculin singulier : calme ne change pas.",
   "« Les filles sont contentes. » Le sujet les filles → elles : féminin pluriel. L'adjectif content devient contentes (e + s).",
   "« Les garçons semblent prêts. » Sembler est un verbe d'état ; le sujet les garçons → ils : masculin pluriel. Prêt prend s, et son accent circonflexe est conservé : prêts."],
  "common_errors": ["Accorder l'attribut avec le mot qui suit au lieu du sujet : dans « Les routes sont longues », longues s'accorde avec routes, pas avec le verbe.",
   "Laisser l'adjectif invariable : « Les garçons semblent prêt » est faux ; le sujet est pluriel.",
   "Confondre attribut et COD : après un verbe d'action, un groupe peut être COD ; après être ou sembler, l'adjectif est attribut du sujet."]},

 "CM2-FR-PHRASE": {
  "prerequisites": ["Trouver les verbes conjugués d'une phrase.",
   "Connaître l'infinitif et le participe passé."],
  "discovery": "« Il pleut et je rentre. » « Léa lit. » « Léa lit et Tom dessine. »\nCes phrases n'ont pas la même taille — et ce n'est pas une question de mots : c'est une question de verbes conjugués. Compte-les, et tu sauras tout de suite de quel type de phrase il s'agit.",
  "explanation": "Une phrase simple contient un seul verbe conjugué : « Léa lit. » Une phrase complexe en contient plusieurs : « Léa lit et Tom dessine. » « Il pleut et je rentre » réunit deux faits, donc deux verbes conjugués : c'est une phrase complexe.\nLe piège vient des temps composés. « Elle a chanté » paraît fait de deux mots, mais l'auxiliaire a et le participe passé chanté forment un seul verbe conjugué au passé composé. De même, l'infinitif n'est pas une forme conjuguée : dans « avant de partir », partir ne change ni avec le sujet ni avec le temps.\nPourquoi compter les verbes ? Parce que chaque verbe conjugué appelle son sujet, et que la phrase complexe relie plusieurs propositions. Cela guide la ponctuation, les virgules devant et, ou, mais, et la relecture des accords. Un bon réflexe : entoure chaque verbe conjugué au crayon ; si ton cercle entoure aussi l'auxiliaire et son participe, compte-les comme un seul.",
  "method": ["Parcours la phrase et repère les formes qui changent avec le temps ou le sujet : ce sont les verbes conjugués.",
   "Compte un auxiliaire (avoir/être) et son participe passé comme un seul verbe : a chanté = un verbe.",
   "Ne compte pas les infinitifs (partir) ni les participes employés comme adjectifs.",
   "Un seul verbe conjugué → phrase simple ; plusieurs → phrase complexe.",
   "Vérifie que chaque verbe conjugué a bien un sujet pour accorder correctement."],
  "worked_example": ["« Le chien dort. » Un seul verbe conjugué, dort : phrase simple.",
   "« Le chien dort pendant que le chat joue. » Deux verbes conjugués, dort et joue, réunis par pendant que : phrase complexe.",
   "« Elle a chanté avant de partir. » A chanté est un seul verbe au passé composé ; partir est à l'infinitif. Un seul verbe conjugué : phrase simple, malgré les quatre mots verbaux."],
  "common_errors": ["Compter « a chanté » comme deux verbes : l'auxiliaire et le participe passé forment un seul verbe conjugué.",
   "Compter un infinitif comme un verbe conjugué : dans « avant de partir », partir n'est conjugué à aucun temps.",
   "S'arrêter au premier verbe et rater celui d'une seconde proposition reliée par et, ou, pendant que…"]},

 "CM2-FR-HOMOPHONES": {
  "prerequisites": ["Connaître le verbe avoir au présent.",
   "Savoir ce qu'est une préposition (à, de, en…)."],
  "discovery": "Sur une carte postale : « Lina a un cadeau à offrir. » Les deux mots en gras se prononcent exactement pareil.\nPourtant l'un est un verbe qui peut changer de temps, et l'autre un petit mot invariable qui relie. Comment choisir sans se tromper ? Avec un remplacement magique : avait.",
  "explanation": "A (sans accent) est une forme du verbe avoir au présent : il a, elle a. Comme tout verbe, on peut le changer de temps : hier, il avait un cadeau. Si le remplacement par avait fonctionne, écris a.\nÀ (avec accent) est une préposition : un mot invariable qui relie des éléments, comme dans aller à Paris, un cadeau à offrir. Aucun verbe ne se cache là : le remplacement par avait est impossible — « je vais avait Paris » ne veut rien dire.\nLa méthode est donc un test, pas un souvenir : lis la phrase, remplace le mot qui gêne par avait, puis relis toute la phrase. Si elle reste correcte, c'est le verbe a. Si elle casse, c'est la préposition à. Attention au cas de l'auxiliaire : dans « il a fini », a est le verbe avoir qui aide à former le passé composé — le test avait marche encore : il avait fini.\nCe test s'apprend une fois pour toutes et servira pour d'autres homophones : on/ont (test : ils avaient), et/est (test : était). Un remplacement qui marche vaut mieux qu'une impression.",
  "method": ["Repère l'endroit où tu dois écrire a ou à.",
   "Remplace mentalement le mot par avait.",
   "Relis toute la phrase avec avait : la construction reste-t-elle correcte ?",
   "Si oui, écris a (verbe avoir). Si non, écris à (préposition, avec l'accent).",
   "Vérifie aussi le sens : a montre une possession ou une action ; à relie (lieu, destinataire, but…)."],
  "worked_example": ["« Il … un vélo. » Test : Il avait un vélo — correct. On écrit donc a, verbe avoir au présent.",
   "« Elle va … la piscine. » Test : Elle va avait la piscine — impossible. On écrit à, préposition qui introduit le lieu la piscine.",
   "« Mon frère … fini son dessin. » Test : Mon frère avait fini — correct. On écrit a : c'est l'auxiliaire avoir du passé composé a fini."],
  "common_errors": ["Mettre un accent « pour faire joli » : l'accent de à n'est jamais une décoration, il distingue la préposition du verbe.",
   "Tester seulement le mot sans relire la phrase entière : c'est la phrase complète qui reste (ou non) construite avec avait.",
   "Confondre avec la forme as (tu as) : le remplacement par avait fonctionne aussi — tu avais — mais le sujet doit être tu."]},

 "CM2-FR-LEXIQUE": {
  "prerequisites": ["Repérer la partie commune entre deux mots.",
   "Expliquer le sens d'un mot simple."],
  "discovery": "Dans un jardin, le jardinier jardine avec soin. Trois mots, une même idée — et une même partie : jardin.\nMais attention : la vie marine regorge aussi de mots qui se ressemblent sans rien avoir en commun. Lait, laine, laiterie : lequel fait vraiment famille ? Ressembler ne suffit pas ; il faut un lien de sens.",
  "explanation": "Une famille de mots regroupe des mots formés sur une même base et qui gardent un lien de sens. Jardin, jardinier, jardiner, jardinage : la base jardin est visible, et tous parlent du même univers — le jardin. C'est ce double critère, forme ET sens, qui fonde la famille.\nLes mots de la famille se construisent avec un préfixe (placé avant la base : re- dans relire, qui signifie lire encore) ou un suffixe (placé après : -ier dans jardinier, qui désigne la personne). Préfixes et suffixes fabriquent des mots nouveaux à partir de la base, comme des briques ajoutées.\nPourquoi ce réflexe est précieux : les familles de mots aident à l'orthographe. Si tu hésites entre jardin et jardain, pense à jardinier — la base réapparaît et lève le doute. Mais garde le réflexe inverse : quand deux mots se ressemblent sans lien de sens (laine n'a rien à voir avec lait), ils ne font PAS famille, même s'ils commencent pareil.",
  "method": ["Repère la base commune aux mots proposés (la partie qui se répète).",
   "Vérifie le lien de sens : les mots parlent-ils de la même idée ?",
   "Regarde ce qui a été ajouté : un préfixe avant la base (re-, dé-, in-…) ou un suffixe après (-ier, -erie, -age…).",
   "Teste avec un mot dérivé : peut-on former d'autres mots de la même base ?",
   "Conclus : même base + même idée = même famille ; ressemblance seule = pas famille."],
  "worked_example": ["Jardin, jardinier, jardinage : base jardin + suffixes -ier et -age. Tous liés au jardin : même famille.",
   "Relire = re- (encore) + lire. Le préfixe re- ajoute l'idée de répétition : relire, refaire, redire.",
   "Terrain, terrien sont liés à terre. Terrible ressemble à terre par ses premières lettres, mais son sens (qui fait très peur) n'a aucun lien : pas la même famille."],
  "common_errors": ["Regrouper les mots par leur seule écriture : lait et laine commencent par lai, mais l'un vient du lait, l'autre de la laine — pas de lien de sens.",
   "Oublier de vérifier le sens du préfixe : re- ne veut pas dire « contre » (comme dans contredire) ; re- marque la répétition.",
   "Ne pas utiliser les dérivés pour corriger l'orthographe : jardinier prouve l'écriture jardin, sans ail."]},

 "CM2-FR-POLYSEMIE": {
  "prerequisites": ["Lire une phrase complète avant d'interpréter un mot.",
   "Utiliser le contexte pour comprendre."],
  "discovery": "« Une feuille tombe de l'arbre. » « Écris ton prénom sur une feuille. »\nMême mot, deux objets complètement différents — et pourtant aucune erreur : un mot peut tout à fait avoir plusieurs sens. C'est la phrase autour de lui qui dit lequel choisir.",
  "explanation": "Un mot qui a plusieurs sens est un mot polysémique (la polysémie = plusieurs sens). Souris : l'animal, ou l'objet qui commande l'ordinateur. Pied : partie du corps, ou support d'une table, ou unité de poésie. Le dictionnaire présente ces sens numérotés : 1, 2, 3…\nCe qui choisit le bon sens, c'est le contexte : tout ce qui est écrit autour du mot. Dans « la souris grignote du fromage », grignote et fromage désignent l'animal ; dans « je clique avec la souris », cliquer et ordinateur désignent l'objet. Les mots voisins sont tes indices.\nLa méthode : relis la phrase entière, entoure les mots qui entourent le mot étudié, puis essaie chaque sens dans la phrase. Garde celui qui rend la situation logique. Méfie-toi de ta première idée : le sens le plus courant n'est pas forcément le bon ici — dans « le pied de la chaise », personne ne parle d'un orteil.",
  "method": ["Relis la phrase entière qui contient le mot, pas seulement le mot.",
   "Repère les mots voisins qui donnent des indices (actions, objets, lieu).",
   "Liste les sens possibles du mot (comme dans le dictionnaire).",
   "Essaie chaque sens dans la phrase : lequel rend la situation logique ?",
   "Garde ce sens et vérifie-le : remplace mentalement le mot par une définition courte."],
  "worked_example": ["« Pose ton verre sur la table. » Poser indique un objet qu'on tient : verre = le récipient pour boire (et son contenu).",
   "« Le pied de la chaise est cassé. » Chaise et cassé indiquent qu'on parle d'un meuble : pied = la partie qui soutient la chaise.",
   "« La pièce dure une heure au théâtre. » Théâtre et dure une heure orientent vers la scène : pièce = l'œuvre qu'on joue, pas une monnaie ni une salle."],
  "common_errors": ["Choisir d'abord le sens le plus courant sans lire le contexte : dans « le pied de la chaise », le sens « partie du corps » ne convient pas.",
   "Inventer un sens qui n'existe dans aucun dictionnaire : un mot polysémique a plusieurs sens, mais pas une infinité.",
   "Confondre polysémie et synonymes : la polysémie, c'est UN mot avec plusieurs sens ; les synonymes, ce sont des mots différents au sens proche."]},

 "CM2-FR-COMPREHENSION": {
  "prerequisites": ["Prélever une information écrite dans un texte.",
   "Relier deux informations d'un même texte."],
  "discovery": "« Nora ferme son parapluie et secoue ses bottes mouillées. »\nLe texte ne dit jamais « il pleuvait ». Pourtant, tu le comprends tout de suite — parce que ton cerveau a relié des indices : parapluie, bottes, mouillées. C'est une déduction : le texte plus un raisonnement.",
  "explanation": "Une déduction, ce n'est pas une invention : c'est une conclusion appuyée sur des indices écrits dans le texte. Nora ferme son parapluie, ses bottes sont mouillées → elle a probablement marché sous la pluie. Chaque mot de ta réponse doit pouvoir s'appuyer sur un mot du texte.\nLe réflexe professionnel, c'est la formule « … parce que … » : « Sam a probablement froid parce qu'il souffle sur ses doigts et enfile ses gants ». Le parce que oblige à citer l'indice. Sans indice cité, ce n'est plus une déduction, c'est une imagination.\nDistingue trois niveaux : ce qui est écrit (certain), ce que les indices rendent très probable (une bonne déduction se dit avec peut-être ou probablement), et ce qui n'a aucun appui dans le texte (à ne pas écrire). « Nora habite à Lyon » n'a aucun indice : même si c'est plausible, le texte ne permet pas de le dire. Bien déduire, c'est savoir jusqu'où le texte te laisse aller.",
  "method": ["Relis le passage et entoure les détails précis (objets, actions, réactions des personnages).",
   "Demande-toi : que ces indices mis ensemble laissent-ils penser ?",
   "Formule ta réponse avec un adjectif de prudence : peut-être, probablement.",
   "Ajoute « parce que » suivi d'un indice réellement écrit dans le texte.",
   "Relis-toi : chaque information de ta réponse vient-elle du texte ? Sinon, retire-la."],
  "worked_example": ["« Sam enfile ses gants et souffle sur ses doigts. » Déduction : Sam a probablement froid, parce qu'il souffle sur ses doigts et met des gants. Deux indices écrits, une conclusion prudente.",
   "« Inès cache un paquet derrière son dos et sourit en voyant son amie. » Déduction : elle prépare peut-être une surprise, parce qu'elle cache un paquet et qu'elle sourit.",
   "« La salle devient silencieuse. Le rideau se lève. » Déduction : un spectacle va probablement commencer. Le texte ne dit pas lequel : ne va pas au-delà des indices."],
  "common_errors": ["Répondre avec une invention : « Sam habite Paris » ou « Sam a dix ans » n'apparaissent nulle part dans le texte.",
   "Oublier l'indice : dire « Sam a froid » sans le parce que rend la réponse invérifiable.",
   "Annoncer comme certain ce qui n'est que probable : écris probablement ou peut-être quand le texte ne dit pas la chose directement."]},

 "CM2-FR-ECRIT-REDIGER": {
  "prerequisites": ["Écrire une phrase correcte (majuscule, verbe, point).",
   "Relire un texte court pour corriger les accords."],
  "discovery": "Tu racontes ta sortie imaginaire à la bibliothèque : « Léa entre. Le livre est rouge. Milo arrive. Il pleut. »\nTon lecteur tique : qui est Léa ? pourquoi Milo ? que se passe-t-il vraiment ? Les événements existent, mais rien n'est relié. Un bon récit, c'est une chaîne : chaque phrase tire la suivante.",
  "explanation": "Un récit raconte des événements qui s'enchaînent. Avant d'écrire, prépare trois moments : le début (qui ? où ?), l'action principale (que se passe-t-il ?) et la fin (comment cela se termine-t-il ?). Ces trois moments forment le squelette de ton histoire.\nPour que le lecteur te suive, utilise deux outils. Les connecteurs de temps — d'abord, ensuite, puis, enfin — montrent l'ordre des événements. Les reprises — un pronom (il, elle) qui remplace le personnage déjà nommé — évitent les répétitions sans perdre le lecteur : « Milo entre dans la bibliothèque. Il cherche un conte. »\nEnfin, la relecture se fait en trois passes, dans cet ordre : 1) le sens (tout est compréhensible ? l'ordre est logique ?) ; 2) les phrases (majuscule, verbe conjugué, point) ; 3) les accords (sujet-verbe, déterminant-nom-adjectif). Une histoire peut être imaginaire mais doit rester claire : à la relecture, demande-toi si quelqu'un qui ne connaît pas ton histoire peut la comprendre.",
  "method": ["Choisis ton personnage, le lieu et l'événement principal avant d'écrire.",
   "Écris d'abord le squelette : une phrase de début, une pour l'action, une pour la fin.",
   "Relie les événements avec des connecteurs : d'abord, ensuite, puis, enfin.",
   "Garde le même personnage et reprends-le avec un pronom (il, elle) plutôt qu'en le répétant.",
   "Relis en trois passes : le sens, puis les phrases, puis les accords — dans cet ordre."],
  "worked_example": ["Squelette : « D'abord, Léa entre dans la bibliothèque. Ensuite, elle choisit un conte. Enfin, elle repart avec son livre. » Trois moments, trois connecteurs.",
   "Reprise : la deuxième phrase utilise elle au lieu de répéter Léa — le lecteur sait de qui on parle, sans lourdeur.",
   "Relecture d'accords : « Léa et Milo chante » → le sujet est pluriel (ils chantent) → « Léa et Milo chantent ». Une passe de plus sur le sens : le lecteur comprend qui fait quoi, dans quel ordre."],
  "common_errors": ["Changer de personnage sans le présenter : si Milo surgit sans avoir été nommé avant, le lecteur est perdu.",
   "Empiler des phrases sans lien (« Il pleut. Le livre est rouge. ») : chaque phrase doit faire avancer l'histoire.",
   "Sauter la relecture : la plupart des points perdus (accords, ponctuation) se corrigent à la troisième passe."]},

 "CM2-FR-DICTEE-RELECTURE": {
  "prerequisites": ["Accorder déterminant, nom et adjectif.",
   "Connaître les tests des homophones (avait, il)."],
  "discovery": "Tu viens de copier une phrase dictée : « Les petit chats joue. » Quelque chose cloche, mais quoi ?\nSi tu relis « d'un coup d'œil », tu risques de sauter l'erreur : ton œil lit ce qu'il croit avoir écrit. Les bons relecteurs ne relisent pas plus vite — ils relisent par catégories, une seule chose à la fois.",
  "explanation": "La relecture efficace se fait par passes, dans un ordre précis, parce que chaque passe chasse un type d'erreur différent. Passe 1, les accords du groupe nominal : déterminant, nom, adjectif s'accordent ensemble (les petits chats). Passe 2, la conjugaison : remplace le sujet par il/ils ou elle/elles et vérifie la terminaison (les chats → ils → jouent). Passe 3, les homophones : teste avait pour a/à et on/ont, était pour et/est. Passe 4, l'orthographe lexicale : les mots impossibles à déduire (jardin), où les familles de mots aident (jardinier). Passe 5, la ponctuation et les majuscules.\nChaque passe utilise un outil, pas une impression : les remplacements (avaient, il) pour les homophones et la conjugaison ; le nom noyau pour les accords ; les mots dérivés pour l'orthographe. Enfin, une règle d'or : relis lentement, mot à mot, idéalement en surlignant chaque mot lu — sinon l'œil saute les petits mots.\nCette activité entraîne la relecture d'une phrase déjà écrite ; ce n'est pas une dictée audio. Ici, le correcteur classe seulement les mots prévus par l'activité : toute autre modification demande une relecture humaine.",
  "method": ["Passe 1 — groupes nominaux : accorde déterminant, nom, adjectif à partir du nom noyau.",
   "Passe 2 — conjugaison : remplace le sujet par il/ils, elle/elles et vérifie la terminaison du verbe.",
   "Passe 3 — homophones : teste avait (a/à, on/ont) et était (et/est).",
   "Passe 4 — orthographe des mots : pense aux familles (jardinier → jardin).",
   "Passe 5 — ponctuation et majuscules ; puis relis l'ensemble à voix basse."],
  "worked_example": ["« Les petit chats joue. » Passe 1 : chats est masculin pluriel → petits. Passe 2 : les chats → ils → jouent. Résultat : « Les petits chats jouent. »",
   "« Les enfants on des vélo. » Passe 3 : on → avaient ? « Les enfants avaient des vélos » fonctionne → ont. Passe 1 : des annonce un pluriel → vélos. Résultat : « Les enfants ont des vélos. »",
   "« Les enfants chante dans le jardain. » Passe 2 : les enfants → ils → chantent. Passe 4 : jardain → penser à jardinier → jardin. Résultat : « Les enfants chantent dans le jardin. »"],
  "common_errors": ["Relire « d'un coup d'œil » : l'œil corrige tout seul et saute les erreurs ; il faut relire lentement, catégorie par catégorie.",
   "Corriger un mot au hasard sans test : avant de changer on en ont, fais toujours le remplacement par avaient.",
   "Sauter une passe : une belle conjugaison ne sauve pas un accord oublié — chaque type d'erreur demande sa passe."]},

 "CM2-FR-PRESENT": {
  "prerequisites": ["Connaître les pronoms je, tu, il, nous, vous, ils.",
   "Savoir ce qu'est un verbe conjugué."],
  "discovery": "« Aujourd'hui, je … à l'école. » Comment complètes-tu ? Tout dépend du verbe et du sujet : avec être, la phrase devient « je suis à l'école ».\nÊtre est le verbe le plus irrégulier du français : ses formes au présent ne se devinent pas, elles s'apprennent par cœur — et c'est justement pour ça qu'on les travaille.",
  "explanation": "Le présent de l'indicatif dit ce qui se passe maintenant : « Maintenant, je suis en classe. » C'est le temps de la description du moment présent et des vérités générales.\nÊtre est irrégulier : sa base change à chaque personne. Il faut mémoriser le tableau entier : je suis, tu es, il/elle est, nous sommes, vous êtes, ils/elles sont. Aucune logique de terminaison ne remplace cet apprentissage — mais quelques repères aident : trois formes du singulier et du pluriel commencent par s (suis, sommes, sont) ; êtes, avec vous, prend un accent circonflexe.\nPour choisir la forme : identifie le sujet et sa personne (1re, 2e ou 3e ; singulier ou pluriel), puis prends la forme apprise correspondante. Attention aux pronoms : après nous, la forme est sommes ; après vous, êtes ; après ils ou elles, sont. Et garde l'accent circonflexe de êtes : après vous, on écrit êtes, jamais etes.",
  "method": ["Repère le sujet et remplace-le par le bon pronom (je, tu, il, nous, vous, ils).",
   "Identifie la personne : 1re, 2e ou 3e, singulier ou pluriel.",
   "Rappelle-toi la forme apprise du verbe être pour cette personne : suis, es, est, sommes, êtes, sont.",
   "Écris la forme en conservant les accents (es, êtes).",
   "Relis avec le sujet d'origine : la phrase doit rester naturelle au présent."],
  "worked_example": ["Sujet je, verbe être : je suis. « Je suis dans la cour. »",
   "Sujet nous : nous sommes. « Nous sommes en CM2. » Attention, pas de « nous sommes » sans s final.",
   "Sujet elle : elle est. « Elle est dans la cour. » Troisième personne du singulier : la forme courte est."],
  "common_errors": ["Écrire « je es » ou « tu suis » : chaque personne a SA forme — je suis, tu es.",
   "Oublier l'accent circonflexe de êtes : après vous, la forme est êtes.",
   "Mélanger sont (verbe être avec ils) et son (possessif) : « ils sont là » mais « son cartable »."]},

 "CM2-FR-IMPARFAIT": {
  "prerequisites": ["Connaître les pronoms personnels sujet.",
   "Repérer le radical et la terminaison d'un verbe."],
  "discovery": "« Quand j'étais petit, j'avais un vélo rouge. » Raconter son passé, c'est souvent raconter une habitude ou un décor.\nCes phrases ont un point commun : l'imparfait. Et l'imparfait a un secret bien pratique : une seule base, six terminaisons qui ne changent jamais.",
  "explanation": "L'imparfait de l'indicatif sert à décrire ou à raconter une habitude dans le passé : « Chaque été, nous avions des vacances longues. » Il peint un décor, une durée — contrairement au passé composé qui raconte des actions ponctuelles.\nSa formation est la plus régulière des temps français : on prend la base de la forme « nous » du présent (nous avons → av-) et on ajoute les terminaisons -ais, -ais, -ait, -ions, -iez, -aient. J'avais, tu avais, il avait, nous avions, vous aviez, ils avaient. Seul le radical compte : la terminaison ne dépend QUE de la personne.\nPour bien écrire : repère le sujet, trouve sa personne, choisis la terminaison. Les pièges classiques : la 3e personne du singulier finit par -ait (il avait), la 3e du pluriel par -aient (ils avaient) — un seul son, deux écritures, la personne tranche. Et garde le i de -ions/-iez avec nous et vous : nous avions, vous aviez.",
  "method": ["Repère le sujet et sa personne (1re, 2e, 3e ; singulier ou pluriel).",
   "Trouve la base : forme « nous » du présent sans -ons (avoir → nous avons → av-).",
   "Ajoute la terminaison de la personne : -ais, -ais, -ait, -ions, -iez, -aient.",
   "Vérifie la personne des sons proches : il avait (-ait) contre ils avaient (-aient).",
   "Relis la phrase : l'imparfait doit décrire ou raconter une habitude passée."],
  "worked_example": ["Sujet il, verbe avoir : base av- + -ait → il avait. « Il avait un cartable bleu. »",
   "Sujet nous : av- + -ions → nous avions. « Nous avions cours le matin. »",
   "Sujet ils : av- + -aient → ils avaient. Compare : elle avait (une seule personne), elles avaient (plusieurs)."],
  "common_errors": ["Écrire « il avais » ou « ils avait » : la terminaison suit la personne, -ait pour il/elle, -aient pour ils/elles.",
   "Oublier le i de nous avions / vous aviez : ces deux formes gardent le i de la terminaison.",
   "Confondre imparfait et passé composé : l'habitude et la description prennent l'imparfait, l'action ponctuelle le passé composé."]},

 "CM2-FR-FUTUR": {
  "prerequisites": ["Connaître les pronoms personnels sujet.",
   "Repérer le radical d'un verbe."],
  "discovery": "« Demain, j'irai au parc. » « L'année prochaine, nous irons au collège. »\nParler de l'avenir, c'est le rôle du futur simple. Et avec le verbe aller, on ne peut pas deviner la forme : aller prend une base toute nouvelle, ir-, qu'il faut connaître par cœur.",
  "explanation": "Le futur simple situe une action à venir : « Demain, elle ira au parc. » Il promet, prédit ou annonce un projet.\nPour la plupart des verbes, le futur se forme sur l'infinitif (chanter → je chanterai). Mais aller est irrégulier : sa base n'est pas all- mais ir-. Le tableau : j'irai, tu iras, il/elle ira, nous irons, vous irez, ils/elles iront. Ces formes s'apprennent par cœur, d'autant qu'elles sont très utiles : on s'en sert sans arrêt pour parler de l'avenir.\nDeux repères pour éviter les confusions au pluriel : nous irons (avec -ons comme nous allons), vous irez (avec -ez comme vous allez), ils iront (avec -ont, comme ils sont). Singulier : irai/iras/ira s'écrivent avec un seul r et la terminaison -ai, -as, -a. Relis bien : une seule et même base ir-, six terminaisons.",
  "method": ["Repère le sujet et sa personne.",
   "Utilise la base irrégulière ir- du verbe aller au futur.",
   "Ajoute la terminaison : -ai, -as, -a, -ons, -ez, -ont.",
   "Au pluriel, distingue bien nous irons, vous irez, ils iront.",
   "Vérifie le sens : la phrase annonce bien quelque chose qui n'est pas encore arrivé."],
  "worked_example": ["Sujet je : j'irai. « L'été prochain, j'irai à la mer. » Un seul r.",
   "Sujet elle : elle ira. « Demain, elle ira au parc. » Troisième personne du singulier : -a.",
   "Sujet ils : ils iront. « Ils iront au collège. » Terminaison -ont, comme dans ils sont."],
  "common_errors": ["Écrire la base all- au futur (« j'allrai ») : la base du futur d'aller est ir-.",
   "Confondre les terminaisons du pluriel : nous irons / vous irez / ils iront — chaque pronom a la sienne.",
   "Mettre deux r (« irrai ») : au singulier, une seule base ir- suivie de -ai, -as, -a."]},

 "CM2-FR-PASSE-COMPOSE": {
  "prerequisites": ["Connaître avoir au présent.",
   "Reconnaître un participe passé (chanté, fini, pris)."],
  "discovery": "« Hier, elle a chanté toute la journée. » L'action est finie, elle a eu lieu une fois : c'est le passé composé qui raconte.\nCe temps porte bien son nom : il est composé de deux briques — un auxiliaire et un participe passé. Comprendre ces deux briques, c'est savoir l'écrire.",
  "explanation": "Le passé composé raconte une action ponctuelle et terminée dans le passé : « Hier, elle a chanté. » Il se construit avec l'auxiliaire avoir (ou être) au présent, suivi du participe passé du verbe : j'ai chanté, tu as chanté, elle a chanté, nous avons chanté, vous avez chanté, ils ont chanté.\nLes deux briques ont des rôles différents : l'auxiliaire porte la personne et le temps (a est avoir au présent avec elle) ; le participe passé porte le sens (chanté). Ensemble, ils forment UN seul verbe conjugué — c'est pourquoi on dit que « a chanté » est une forme, pas deux verbes.\nPour chanter, le participe passé est chanté (terminaison -é, comme tous les verbes en -er). Écris toujours l'accent aigu : chanté, pas chante. Avec l'auxiliaire avoir et sans complément d'objet direct placé avant le verbe, le participe passé ne s'accorde pas avec le sujet : elle a chanté, elles ont chanté — chanté reste invariable. (L'accord de l'auxiliaire être, lui, se voit dans l'atelier dédié.)",
  "method": ["Repère le sujet et sa personne.",
   "Écris l'auxiliaire avoir au présent qui correspond (ai, as, a, avons, avez, ont).",
   "Ajoute le participe passé du verbe : pour chanter, c'est chanté avec un accent aigu.",
   "N'accorde pas le participe passé avec le sujet quand l'auxiliaire est avoir et qu'aucun COD ne précède.",
   "Relis : auxiliaire + participe passé forment un seul verbe au passé composé."],
  "worked_example": ["Sujet elle, verbe chanter : avoir au présent → a ; participe passé → chanté. « Hier, elle a chanté. »",
   "Sujet nous : avons + chanté → « Nous avons chanté au chœur. »",
   "Sujet ils : ont + chanté → « Ils ont chanté toute la soirée. » Le participe chanté ne prend pas de s : l'auxiliaire est avoir et aucun COD ne le précède."],
  "common_errors": ["Oublier l'accent du participe passé : chanté s'écrit avec un é, comme tous les participes des verbes en -er.",
   "Accorder le participe passé avec le sujet : avec avoir et sans COD placé avant, « elles ont chanté » ne prend pas de s à chanté.",
   "Séparer les deux briques à la relecture : « a chanté » est UN verbe conjugué au passé composé, pas un verbe plus un mot."]},

 "CM2-FR-PASSE-SIMPLE": {
  "prerequisites": ["Connaître le radical d'un verbe en -er.",
   "Lire des récits (contes, romans jeunesse)."],
  "discovery": "« Le soir venu, elle chanta si bien que les oiseaux se turent. »\nOn dirait un conte. C'est le signe du passé simple : le temps des récits écrits, celui des livres qu'on lit — et qu'on apprend à reconnaître puis à employer.",
  "explanation": "Le passé simple est le temps des récits écrits : contes, romans, légendes. Il raconte des actions ponctuelles qui font avancer l'histoire, là où l'imparfait décrivait le décor. À l'oral, on utiliserait plutôt le passé composé ; dans un livre, le passé simple donne au récit son allure.\nPour les verbes en -er comme chanter, les formes se construisent sur le radical chant- : je chantai, tu chantas, il chanta, nous chantâmes, vous chantâtes, ils chantèrent. Repère les accents : accent circonflexe avec nous (chantâmes) et vous (chantâtes) ; terminaison -èrent au pluriel avec ils.\nLe passé simple est surtout un temps de lecture : tu en rencontreras à chaque page de conte (il fut, elle alla, ils virent). Savoir le former pour un verbe en -er t'aide à le reconnaître et à écrire des récits au style livre. Un conseil : relis la forme à voix haute — le son -a (-ai, -as, -a, -èrent) est la signature du temps.",
  "method": ["Repère le sujet et sa personne.",
   "Prends le radical du verbe en -er (chanter → chant-).",
   "Ajoute la terminaison : -ai, -as, -a, -âmes, -âtes, -èrent.",
   "Vérifie les accents : circonflexe pour nous chantâmes et vous chantâtes.",
   "Relis : le son -a et le contexte de récit écrit confirment le passé simple."],
  "worked_example": ["Sujet il, verbe chanter : chant- + -a → il chanta. « Le soir venu, elle chanta. »",
   "Sujet nous : chant- + -âmes → nous chantâmes, avec l'accent circonflexe.",
   "Sujet ils : chant- + -èrent → ils chantèrent. Terminaison -èrent, avec accent grave sur le premier e."],
  "common_errors": ["Oublier les accents : nous chantâmes et vous chantâtes prennent un accent circonflexe ; ils chantèrent un accent grave.",
   "Employer le passé simple à l'oral dans un dialogue courant : c'est un temps surtout écrit ; préfère le passé composé pour parler.",
   "Confondre il chanta (passé simple, une action du récit) avec il chantait (imparfait : une habitude ou un décor)."]},

 "CM2-FR-PLUS-QUE-PARFAIT": {
  "prerequisites": ["Connaître avoir à l'imparfait.",
   "Reconnaître un participe passé."],
  "discovery": "« Elle avait chanté toute la matinée quand ses amis sont arrivés. »\nDeux actions dans le passé — mais l'une a clairement eu lieu AVANT l'autre. Laquelle ? C'est exactement le travail du plus-que-parfait : super-organisateur du passé.",
  "explanation": "Le plus-que-parfait situe une action avant une autre action passée : « Elle avait chanté avant de rentrer » — chanter a eu lieu avant le retour. C'est le passé du passé : quand tu racontes au passé et que tu dois dire « encore avant », le plus-que-parfait entre en scène.\nSa construction associe deux briques déjà connues : l'auxiliaire avoir (ou être) à l'IMPARFAIT, suivi du participe passé. Pour chanter : j'avais chanté, tu avais chanté, il avait chanté, nous avions chanté, vous aviez chanté, ils avaient chanté.\nLa logique des briques guide l'écriture : c'est l'auxiliaire à l'imparfait qui porte la personne (terminaisons -ais, -ais, -ait, -ions, -iez, -aient) ; le participe passé porte le sens et son accent (chanté). Avec avoir et sans COD placé avant, le participe ne s'accorde pas avec le sujet : elle avait chanté, elles avaient chanté. Le repère d'identification à la lecture : un auxiliaire à l'imparfait suivi d'un participe passé — voilà un plus-que-parfait.",
  "method": ["Repère les deux actions passées et décide laquelle est arrivée avant : c'est elle qui sera au plus-que-parfait.",
   "Écris l'auxiliaire avoir à l'imparfait selon la personne (avais, avais, avait, avions, aviez, avaient).",
   "Ajoute le participe passé : pour chanter, chanté avec son accent aigu.",
   "N'accorde pas le participe avec le sujet : l'auxiliaire est avoir et aucun COD ne précède.",
   "Relis : l'action au plus-que-parfait doit être antérieure à l'autre action passée."],
  "worked_example": ["Sujet elle, verbe chanter : avait + chanté → elle avait chanté. « Elle avait chanté avant de rentrer. »",
   "Sujet nous : avions + chanté → nous avions chanté toute la matinée.",
   "Ordre des actions : « Elle avait chanté quand ses amis sont arrivés » — le chant est antérieur : plus-que-parfait ; l'arrivée est le moment repère : passé composé."],
  "common_errors": ["Confondre auxiliaire de l'imparfait et du présent : il avait chanté (plus-que-parfait) n'est pas il a chanté (passé composé).",
   "Oublier l'accent du participe : chanté garde son é comme au passé composé.",
   "Accorder le participe passé avec le sujet : avec avoir et sans COD placé avant, chanté reste invariable."]},

 "CM2-FR-CIRCONSTANCES": {
  "prerequisites": ["Trouver le verbe conjugué et son sujet.",
   "Reconnaître un groupe de mots dans une phrase."],
  "discovery": "« Ce matin, Maya lit dans le jardin. »\nFerme les yeux et joue la scène : tu sais QUAND elle lit (ce matin) et OÙ elle lit (dans le jardin). Deux petits groupes transforment la phrase en image précise. Et si on les enlevait ? « Maya lit. » La phrase tient encore debout : voilà le signe qu'on a affaire à des compléments circonstanciels.",
  "explanation": "Un complément circonstanciel (CC) précise les circonstances de l'action : le lieu (où ?), le temps (quand ?), la cause (pourquoi ?), parfois la manière. Dans « À cause de la pluie, le match est annulé », le groupe explique POURQUOI le match est annulé : c'est un CC de cause.\nLeur signature, c'est la mobilité : un CC peut se déplacer dans la phrase (« Dans le jardin, Maya lit ce matin ») ou être supprimé (« Maya lit ») sans casser la construction. C'est LE test qui les distingue des compléments d'objet : retire « un film » de « Maya regarde un film » et la phrase ne veut plus rien dire — un COD est indispensable, un CC est une précision.\nComment repérer leur type ? Pose les questions : quand ? (CC de temps : ce matin, hier, le soir), où ? (CC de lieu : dans le jardin, sous le préau), pourquoi ? (CC de cause : à cause de la pluie, parce qu'il pleuvait). Souvent introduits par une préposition (dans, sous, à, à cause de) ou une conjonction (quand, parce que), ils enrichissent le récit en situant la scène — mais n'entrent pas dans l'accord du verbe.",
  "method": ["Repère le verbe conjugué et son sujet, puis les groupes restants.",
   "Pour chaque groupe, teste la suppression : la phrase reste-t-elle construite ? Si oui, c'est un complément circonstanciel.",
   "Teste aussi le déplacement : un CC peut changer de place.",
   "Pose la question pour le classer : quand ? (temps), où ? (lieu), pourquoi ? (cause).",
   "Attention aux COD : ils ne peuvent être ni supprimés ni déplacés librement — le sens en dépend."],
  "worked_example": ["« Hier, Paul dessinait dans sa chambre. » Deux CC : hier (quand ? → temps) et dans sa chambre (où ? → lieu). Je peux écrire « Dans sa chambre, Paul dessinait hier » : les deux groupes se déplacent.",
   "« Le soir, Lila raconte une histoire. » Le soir répond à quand ? (CC de temps) et se déplace ; une histoire complète raconte (quoi ?) : c'est un COD, on ne peut pas le supprimer.",
   "« À cause de la pluie, le match est annulé. » Le groupe répond à pourquoi ? : CC de cause. On peut le déplacer : « Le match est annulé à cause de la pluie. »"],
  "common_errors": ["Croire que tout groupe introduit par une préposition est un CC : « Je pense à mon ami » — à mon ami complète le verbe penser (COI), il ne peut pas être supprimé.",
   "Supprimer le CC et la phrase se casse : si « Maya regarde un film » privé de « un film » ne veut plus rien dire, c'est que un film n'est pas un CC.",
   "Confondre la question du CC : « ce matin » répond à quand ?, jamais à où ? — classe chaque CC avec SA question."]},

 "CM2-FR-PRONOMS": {
  "prerequisites": ["Connaître les pronoms il, elle, ils, elles.",
   "Accorder un verbe avec son sujet."],
  "discovery": "« Zoé ouvre un livre. Elle lit la première page. »\nQui est elle ? Tu as répondu « Zoé » sans hésiter — pourtant, le mot Zoé n'apparaît qu'une fois. Le pronom elle a pris le relais : c'est la chaîne des personnages, et ta mission est de la suivre sans la casser.",
  "explanation": "Un pronom personnel (il, elle, ils, elles, mais aussi je, tu, nous, vous, on) reprend un nom ou un groupe déjà cité : on dit son antécédent. « Zoé ouvre un livre. Elle lit la première page » : elle reprend Zoé. Ce système évite les répétitions lourdes — imagine « Zoé ouvre un livre. Zoé lit la première page de Zoé » !\nPour trouver qui un pronom désigne, remonte à la phrase précédente et cherche le nom qui a le même genre et le même nombre : elle ne peut reprendre qu'un féminin singulier (Zoé, la classe), ils qu'un masculin pluriel ou un mélange (les oiseaux, Tom et ses cousins). Puis vérifie avec le SENS : le pronom peut-il vraiment faire l'action ? « Le sac, elle entre en classe » — un sac n'entre pas en classe : elle reprend la personne.\nParfois la reprise reste ambiguë : « Tom rencontre ses cousins. Ils portent tous un manteau rouge » — ils désigne les cousins, ou Tom avec les cousins ? Quand le doute persiste, le remède est d'écrire le nom : « Les cousins portent tous un manteau rouge. » Bien suivre les pronoms, c'est garantir qu'à chaque instant, le lecteur sait de qui on parle.",
  "method": ["Repère le pronom et observe son genre et son nombre (elle = féminin singulier, ils = masculin pluriel…).",
   "Remonte dans les phrases précédentes pour trouver les noms possibles (l'antécédent).",
   "Garde seulement les noms qui ont le même genre et le même nombre.",
   "Vérifie avec le sens : le candidat peut-il vraiment faire l'action du verbe ?",
   "Si plusieurs candidats restent, lève l'ambiguïté en réécrivant le nom au lieu du pronom."],
  "worked_example": ["« Léa pose son sac. Elle entre en classe. » Elle est féminin singulier : candidates, Léa et la classe. Le sac ne peut pas entrer de lui-même ; la classe n'a pas posé de sac : elle reprend Léa.",
   "« Les oiseaux s'envolent. Ils passent au-dessus du toit. » Ils est masculin pluriel et sujet de passent : il reprend les oiseaux.",
   "« Les filles arrivent. Elles sourient. » Réécrivons la répétition avec le bon pronom : Les filles arrivent. Elles sourient. Elles reprend les filles, féminin pluriel, sujet de sourient."],
  "common_errors": ["Prendre le nom le plus proche sans vérifier le sens : « Léa pose son sac. Elle entre » — le sac est plus proche, mais c'est bien Léa qui entre.",
   "Négliger le genre et le nombre du pronom : ils ne peut pas reprendre une seule fille ; elle ne peut pas reprendre les garçons.",
   "Laisser une ambiguïté : si le pronom peut désigner deux groupes, écris le nom pour que le lecteur sache de qui on parle."]},

 "CM2-FR-EXPANSIONS": {
  "prerequisites": ["Repérer le nom noyau d'un groupe nominal.",
   "Connaître les prépositions de, à, en."],
  "discovery": "Une annonce : « un sac ». Trop vague — lequel ? « Un sac bleu » ? « Un sac de sport » ?\nDeux façons de préciser, deux outils différents : un adjectif qui colle au nom, ou un groupe introduit par une petite préposition. Reconnaître lequel tu as sous les yeux, c'est l'objectif de cet atelier.",
  "explanation": "Le nom est le noyau du groupe nominal ; autour de lui, on peut ajouter des expansions qui précisent. Deux nous intéressent ici. L'adjectif épithète se place à côté du nom, sans mot de liaison : « un sac bleu », « un petit jardin ». Le complément du nom est introduit par une préposition — le plus souvent de, aussi à ou en : « un sac de sport », « un bateau à voiles », « une robe en coton ».\nLe test est simple : entre le nom et la précision, y a-t-il une préposition (de, à, en…) ? Non → adjectif épithète. Oui → complément du nom. Attention, le complément du nom précise bien LE NOM (de quoi est fait le sac, à quoi sert le bateau), pas le verbe : dans « un bateau à voiles », à voiles dit quel genre de bateau.\nCes deux outils s'accumulent : « un petit chemin de campagne » combine l'épithète petit et le complément de campagne. Dans une écriture riche, savoir les distinguer permet de varier les précisions : plutôt que trois adjectifs alignés, un complément du nom apporte souvent une information plus concrète (un sac de cuir dit plus que un sac joli).",
  "method": ["Repère le nom noyau du groupe nominal.",
   "Regarde la précision : un seul mot adjectif, ou un groupe de mots ?",
   "Cherche une préposition (de, à, en…) entre le nom et la précision : s'il y en a une, c'est un complément du nom.",
   "Sans préposition, la précision est un adjectif épithète du nom.",
   "Pour enrichir un GN, combine les deux : « un chemin » → « un petit chemin de campagne »."],
  "worked_example": ["« Une veste rouge » : rouge est un adjectif épithète, collé au nom veste sans préposition — il indique une couleur.",
   "« Un bateau à voiles » : à voiles est introduit par la préposition à et précise le nom bateau (quel genre de bateau ?) — c'est un complément du nom.",
   "« Un petit chemin de campagne » : deux expansions — petit (épithète) et de campagne (complément du nom) — autour du noyau chemin."],
  "common_errors": ["Appeler complément du nom tout groupe avec de : dans « le livre de Léa est sur la table », de Léa précise le nom livre (à qui appartient-il ?) — complément du nom ; mais dans « Léa parle de son livre », de son livre complète le verbe (COI).",
   "Confondre précision du nom et précision du verbe : « à voiles » précise bateau, pas un verbe d'action.",
   "Oublier que l'épithète s'accorde avec son nom : « une veste bleu » est faux ; bleue prend un e."]},

 "CM2-FR-PARTICIPE-ETRE": {
  "prerequisites": ["Connaître être au présent.",
   "Accorder un adjectif avec un nom (genre et nombre)."],
  "discovery": "Tu racontes l'arrivée de tes amies : « Elles sont arrivées de bonne heure. »\nÉcoute la fin du mot : arrivées, avec un e et un s. Ce n'est pas un caprice : le participe passé s'est accordé avec le sujet, comme un adjectif. Avec l'auxiliaire être, la terminaison raconte l'histoire du sujet.",
  "explanation": "Au passé composé avec l'auxiliaire être, le participe passé s'accorde avec le sujet en genre et en nombre : Lina est arrivée (Lina, féminin singulier → e) ; Lina et Zoé sont arrivées (féminin pluriel → e + s) ; les garçons sont partis (masculin pluriel → s). La terminaison du participe fonctionne comme celle d'un adjectif : elle recopie le genre et le nombre du sujet.\nLa méthode en trois gestes : 1) vérifie l'auxiliaire (être, pas avoir) ; 2) repère le sujet et remplace-le par il, elle, ils ou elles pour entendre son genre et son nombre ; 3) accorde le participe : e pour le féminin, s pour le pluriel. Un seul être ou une seule chose → singulier ; plusieurs → pluriel.\nDeux frontières à connaître. D'abord, les verbes pronominaux (se laver, se lever) suivent des règles particulières : ils ne sont pas étudiés dans cet atelier. Ensuite, avec l'auxiliaire avoir, la règle est différente : sans complément d'objet direct placé avant le verbe, le participe ne s'accorde pas (elle a chanté). C'est bien l'auxiliaire être qui déclenche l'accord avec le sujet ici.",
  "method": ["Vérifie l'auxiliaire : le participe s'accorde avec le sujet quand il est construit avec être.",
   "Repère le sujet du verbe.",
   "Remplace le sujet par il, elle, ils ou elles : tu entends son genre et son nombre.",
   "Accorde le participe passé comme un adjectif : e pour le féminin, s pour le pluriel (es pour féminin pluriel).",
   "Relis l'ensemble : la terminaison du participe doit recopier le sujet."],
  "worked_example": ["« Nora est … (arrivé). » Sujet Nora → elle : féminin singulier. Avec être, le participe s'accorde : Nora est arrivée.",
   "« Les garçons sont … (parti). » Sujet les garçons → ils : masculin pluriel. Participe accordé : partis.",
   "« Les feuilles sont … (tombé). » Sujet les feuilles → elles : féminin pluriel. Accord complet : tombées (e + s)."],
  "common_errors": ["Accorder avec le mauvais mot : le participe s'accorde avec le SUJET, jamais avec l'auxiliaire ni avec un complément placé après.",
   "Oublier la moitié de l'accord : « elles sont arrivés » rate le e du féminin ; « la porte est fermés » rate le singulier.",
   "Étendre la règle à l'auxiliaire avoir : avec avoir et sans COD placé avant, le participe reste invariable (elle a chanté) — la règle de cet atelier vaut pour être."]},

 "CM2-FR-ON-ONT": {
  "prerequisites": ["Connaître avoir au présent (ils ont).",
   "Savoir remplacer un sujet par un pronom."],
  "discovery": "« On prépare le goûter. Les enfants ont faim. »\nDeux petits mots de trois lettres, un seul son — et deux métiers totalement différents : l'un remplace le sujet, l'autre est un verbe. Pour les départager, deux remplaçants : il et avaient.",
  "explanation": "On est un pronom sujet : il remplace le groupe qui fait l'action et se substitue à il/elle. « On prépare le goûter » devient « il prépare le goûter » : la phrase reste construite avec un pronom sujet — donc on convient.\nOnt (avec t) est le verbe avoir au présent, à la troisième personne du pluriel : elles ont, ils ont. « Les enfants ont faim » devient « les enfants avaient faim » au passé : le remplacement par avaient fonctionne — donc ont convient. On le reconnaît aussi à sa place : ont suit un sujet pluriel et précède souvent un nom ou un participe passé (ont terminé).\nLa méthode est un double test à faire dans l'ordre : essaie il — si la phrase reste correcte, écris on. Sinon, essaie avaient — si la phrase devient un passé correct, écris ont. Relis toujours la phrase complète avec le remplaçant : c'est elle qui valide, pas l'impression. Ce réflexe est le même que pour a/à (test avait) et préparera et/est (test était) : face aux homophones, un remplacement vaut mieux qu'un doute.",
  "method": ["Repère l'endroit où écrire on ou ont.",
   "Premier test : remplace par il. La phrase reste-t-elle correcte ? → on (pronom sujet).",
   "Second test : remplace par avaient. La phrase devient-t-elle un passé correct ? → ont (verbe avoir).",
   "Relis la phrase entière avec le mot choisi.",
   "Vérifie la place : ont suit un sujet pluriel (les enfants, elles) et ne remplace jamais le sujet lui-même."],
  "worked_example": ["« … entend les oiseaux. » Test : Il entend les oiseaux — correct. On écrit on, pronom sujet.",
   "« Les élèves … leurs cahiers. » Test : Les élèves avaient leurs cahiers — correct. On écrit ont, verbe avoir au présent.",
   "« Elles … terminé la lecture. » Test : Elles avaient terminé — correct. On écrit ont : c'est l'auxiliaire avoir du passé composé ont terminé."],
  "common_errors": ["Écrire ont comme pronom sujet : « ont va à la piscine » ne supporte ni il ni avaient — c'est on.",
   "Écrire on comme verbe : « Les enfants on faim » ne supporte pas avaient : seul ont, le verbe avoir, convient — d'où l'importance du test systématique.",
   "Se fier au son : on et ont sont homophones exacts ; seul le test du remplacement (il / avaient) tranche toujours."]},

 "CM2-FR-SYNONYMES": {
  "prerequisites": ["Expliquer le sens d'un mot simple.",
   "Relire une phrase pour en vérifier le sens."],
  "discovery": "Ton personnage est « content ». À force de répéter ce mot, ta page s'ennuie.\nTu pourrais écrire joyeux, heureux, ravi… mais attention : ces cousins ne sont pas interchangeables partout. Un synonyme, ce n'est pas un mot identique — c'est un mot de sens proche, et le contexte décide.",
  "explanation": "Des synonymes sont des mots de sens proche : content et heureux, immense et très grand, chuchoter et parler à voix basse. Ils permettent d'éviter les répétitions et de choisir le mot juste — plus fort, plus précis, plus joli.\nMais deux synonymes ne sont jamais parfaitement identiques : chacun garde ses habitudes de sens et de construction. « Un exercice difficile » devient « un exercice compliqué » sans perte ; en revanche, dans « un vent fort », puissant convient (un vent puissant), mais courageux serait absurde — le vent n'a pas de courage, même si un personnage fort peut être courageux. Le mot doit garder le sens ET se marier avec les mots de la phrase.\nLa méthode : repère ce que le mot décrit (taille ? émotion ? manière ?), propose des candidats de sens proche, puis relis la phrase entière avec chaque candidat. Garde celui qui conserve le sens voulu et une construction naturelle. En cas de doute, le dictionnaire des synonymes existe — mais c'est la relecture en contexte qui juge.",
  "method": ["Repère ce que le mot décrit dans la phrase : une taille, une émotion, une manière d'agir…",
   "Propose des mots de sens proche (aide-toi de tes lectures ou d'un dictionnaire de synonymes).",
   "Relis la phrase entière avec chaque candidat à la place du mot.",
   "Garde celui qui conserve le sens voulu sans casser la construction.",
   "Vérifie les accords si le candidat est un adjectif (contente → heureuse au féminin)."],
  "worked_example": ["« Une maison immense » → « une maison très grande » : immense signifie très grande ; ancienne parlerait de l'âge, pas de la taille.",
   "« Il chuchote pour ne pas réveiller le bébé » : le but (ne pas réveiller) montre que chuchoter = parler à voix basse, pas parler fort.",
   "« Lina est contente de retrouver son amie » → « Lina est heureuse de retrouver son amie » : le sens est conservé et l'accord au féminin respecté ; joyeuse conviendrait aussi."],
  "common_errors": ["Remplacer sans relire : un synonyme choisi hors contexte peut changer le sens de toute la phrase.",
   "Croire que les synonymes sont interchangeables partout : fort convient pour le vent et pour un personnage ; courageux seulement pour une personne.",
   "Oublier l'accord : contente remplacé par ravi doit devenir ravie au féminin."]},

 "CM2-FR-ANTONYMES": {
  "prerequisites": ["Expliquer le sens d'un mot dans une phrase.",
   "Connaître la notion de préfixe."],
  "discovery": "Sur une porte de boutique : « ouvert ». Sur la porte voisine : « fermé ».\nDeux panneaux, deux mondes — et une idée unique : le contraire. Mais attention : le contraire d'un mot dépend de la phrase où il se trouve, et certains contraires se fabriquent avec un petit préfixe collé au début.",
  "explanation": "Des antonymes sont des mots de sens contraire : ouvert/fermé, lourd/léger, facile/difficile. Choisir le bon antonyme demande de regarder le sens du mot DANS la phrase : le contraire de silencieux, pour un lieu, est bruyant ; le contraire de loin est proche — chaque sens appelle son contraire.\nCertains antonymes se forment avec un préfixe ajouté au début du mot : possible → impossible (préfixe in-), exacte → inexacte, patient → impatient. Le préfixe inverse le sens. Mais attention : ce préfixe s'adapte à la première lettre du mot — in- devant la plupart des lettres, im- devant m, p, b (impossible, impoli, imberbe…). Et tous les mots n'acceptent pas ce procédé : le contraire de facile n'est pas infacile, mais difficile ; le contraire de plein n'est pas inplein, mais vide.\nLa méthode : d'abord, clarifie le sens du mot dans SA phrase (de quoi parle-t-on ?). Ensuite, imagine la situation opposée, sans changer de sujet : une valise pleine ↔ une valise vide. Enfin, si aucun mot contraire ne vient, essaie le préfixe in-/im- — et vérifie dans le dictionnaire que le mot obtenu existe vraiment.",
  "method": ["Clarifie d'abord le sens du mot dans sa phrase (une masse ? un son ? un niveau ?).",
   "Imagine la situation exactement opposée, sans changer de sujet ni de contexte.",
   "Propose le mot contraire qui décrit cette situation (lourd → léger pour une masse).",
   "Si aucun mot simple ne vient, essaie le préfixe in- (im- devant m, p, b) et vérifie que le mot existe.",
   "Contrôle final : les deux mots doivent pouvoir décrire la même chose dans deux situations opposées."],
  "worked_example": ["Contraire de silencieux dans « un lieu silencieux » : le contraire d'un lieu où l'on entend peu est un lieu bruyant — pas lointain, qui parle de distance.",
   "« Cette réponse est exacte » → inexacte : le préfixe in- inverse le sens d'exacte. Précise, lui, est un synonyme, pas un contraire.",
   "« Une valise pleine » → une valise vide : la situation opposée, sans changer de sujet (la valise). Pas de préfixe ici : inplein n'existe pas."],
  "common_errors": ["Chercher un contraire universel : le contraire dépend du sens en jeu — le contraire de fort n'est pas toujours faible (pour un vent : fort/doux).",
   "Ajouter le préfixe au hasard : infacile n'existe pas ; le contraire de facile est difficile. Vérifie toujours l'existence du mot formé.",
   "Confondre antonyme et synonyme : précise n'est pas le contraire d'exacte — c'est un mot de sens proche."]},

 "CM2-FR-DICTIONNAIRE": {
  "prerequisites": ["Connaître l'ordre alphabétique.",
   "Repérer la première lettre différente entre deux mots."],
  "discovery": "Tu cherches canal dans le dictionnaire. Tu ouvres à la page des mots en c… mais là, cahier, caisse, calendrier, camion défilent dans un ordre mystérieux.\nComment le dictionnaire sait-il qui vient avant qui ? En comparant les lettres une à une, de gauche à droite. Et une fois l'article trouvé, une autre question t'attend : quel sens choisir ?",
  "explanation": "Le dictionnaire range les mots dans l'ordre alphabétique — mais pas seulement avec la première lettre. On compare les lettres de gauche à droite, et c'est la PREMIÈRE lettre différente qui décide : carte et chat commencent par c, mais ensuite a vient avant h — donc carte avant chat. De même cahier, canal, carte : les trois commencent par ca, puis h, n, r se classent dans l'ordre de l'alphabet.\nUne fois l'article trouvé, apprends à le lire : le mot vedette (canal), sa classe (n. m. = nom masculin), parfois plusieurs sens numérotés. « Banc, nom masculin : 1. siège long ; 2. groupe de poissons » : l'article annonce deux sens, et la phrase où tu as rencontré le mot désigne lequel — dans « un banc de sardines », c'est le sens 2.\nCette double compétence — chercher vite et choisir le bon sens — fait du dictionnaire un outil de lecture ET d'écriture : vérifier l'orthographe d'un mot, trouver sa classe, ses synonymes, un sens oublié. Les abréviations courantes s'apprennent une fois : n. (nom), v. (verbe), adj. (adjectif), m./f. (masculin/féminin).",
  "method": ["Pour classer deux mots, compare leurs lettres de gauche à droite, position par position.",
   "Arrête-toi à la première lettre différente : celle qui vient avant dans l'alphabet décide de l'ordre.",
   "Dans le dictionnaire, lis l'article complet : mot vedette, classe (n. m., v., adj.), sens numérotés.",
   "Pour choisir un sens, relis la phrase où le mot apparaît et prends le numéro qui convient.",
   "Vérifie l'orthographe du mot en repartant de l'article : c'est la référence officielle."],
  "worked_example": ["Classer lapin, arbre, bateau : a avant b avant l — arbre, bateau, lapin.",
   "Classer cahier, canal, carte : les trois commencent par ca ; ensuite h avant n avant r — cahier, canal, carte.",
   "Article « banc, nom masculin : 1. siège long ; 2. groupe de poissons ». Dans « un banc de sardines », sardines indique des poissons : choisir le sens 2."],
  "common_errors": ["Classer avec la seule première lettre : canal et carte commencent par ca — il faut aller voir la troisième lettre (n avant r).",
   "Choisir le premier sens de l'article sans relire la phrase : le dictionnaire donne TOUS les sens ; le contexte choisit.",
   "Ignorer la classe du mot : lire n. m. (nom masculin) ou v. (verbe) évite de confondre des emplois."]},

 "CM2-FR-LECTURE-ENQUETE": {
  "prerequisites": ["Lire un court récit en entier.",
   "Repérer personnages, lieux et actions."],
  "discovery": "À la bibliothèque, le héros d'une histoire a perdu son livre. Pour le retrouver avec lui, tu mènes l'enquête : qui ? où ? quand ? que fait-il, et dans quel ordre ?\nUn lecteur-enquêteur ne devine pas : il prélève. Chaque réponse est écrite quelque part dans le texte — à toi de la repérer et de la citer.",
  "explanation": "Une information explicite est une information écrite noir sur blanc dans le texte : « Ada pose son sac près de la fenêtre » dit exactement où est le sac. La trouver, c'est faire un prélèvement : je lis, je repère, je cite.\nTrois familles d'indices aident l'enquête. Les personnages et leurs reprises (Ada… elle) : suis la chaîne pour savoir qui agit. Les lieux et les objets (près de la fenêtre, la petite poche) : ils répondent aux questions où ? et quoi ?. L'ordre des actions, souvent signalé par des connecteurs (d'abord, puis, ensuite, enfin) ou par la place des phrases : une action racontée avant une autre a eu lieu avant elle.\nLe geste professionnel, c'est la justification : réponds, puis cite la phrase du texte qui le prouve. « Où retrouve-t-elle sa carte ? Dans la petite poche de son sac, car le texte dit : la carte y était restée. » Sans citation, une réponse reste une opinion ; avec elle, c'est une preuve. C'est la différence entre lire et vraiment lire.",
  "method": ["Lis le texte en entier une première fois, puis relis la question.",
   "Repère les indices : personnages (et leurs pronoms), lieux, objets, connecteurs de temps.",
   "Prélève la phrase qui contient la réponse — surligne-la ou note-la.",
   "Réponds avec les mots du texte quand c'est possible, sans ajouter d'information.",
   "Justifie en citant la phrase : « … car le texte dit : … »."],
  "worked_example": ["« Ada pose son sac près de la fenêtre, puis cherche un conte. » Où pose-t-elle son sac ? Prélèvement : près de la fenêtre — c'est écrit mot pour mot.",
   "« Ada trouve un livre. Elle le fait enregistrer, puis le range dans son sac. » L'ordre du récit donne l'ordre des actions : trouver → enregistrer → ranger (le connecteur puis confirme).",
   "« Ada ne retrouve plus sa carte. Elle vide la petite poche de son sac : la carte y était restée. » Où est la carte ? Dans la petite poche — le texte le dit, et y reprend cet endroit : réponse prouvée."],
  "common_errors": ["Répondre de mémoire sans retourner au texte : la réponse doit être écrite quelque part dans le passage.",
   "Confondre l'ordre du récit et l'ordre des actions : si le texte dit « trouve, puis range », c'est cet ordre-là qui compte.",
   "Ajouter une information plausible mais absente : si le texte ne dit pas que la carte était bleue, ne l'écris pas."]},

 "CM2-FR-RESUMER": {
  "prerequisites": ["Lire un récit court en entier.",
   "Repérer les personnages et les actions principales."],
  "discovery": "Tu viens de finir un livre et ton ami demande : « C'est quoi, l'histoire ? »\nTu as deux solutions : tout raconter mot pour mot (et il s'endort), ou garder l'essentiel (et il veut le lire). Résumer, c'est cet art : dire toute l'histoire… avec moins de mots.",
  "explanation": "Un résumé garde ce qui est indispensable pour comprendre l'histoire : les personnages, le problème ou l'événement principal, et la fin. Il respecte l'ordre du récit et n'invente rien : chaque information du résumé vient du texte.\nLe tri se fait avec une question-radar : « si je retire cette information, l'histoire reste-t-elle compréhensible ? » Oui → c'est un détail, retire-le (la couleur du bonnet). Non → garde-la (la perte du bonnet, l'aide du voisin). Attention : un détail peut devenir indispensable si l'histoire change quand on le retire — c'est le test qui décide, pas la taille du mot.\nLe résumé se rédige avec tes propres mots, en une ou deux phrases courtes : sujet + verbe + complément, sans les dialogues ni les descriptions. Un contrôle qualité en trois points avant de rendre : 1) tout l'essentiel y est (début, événement, fin) ; 2) aucun élément inventé ; 3) l'ordre du récit est respecté. Résumer entraîne une compétence plus large : identifier ce qui compte — la même que pour prendre des notes ou expliquer un film.",
  "method": ["Lis le récit en entier, puis liste les événements dans l'ordre (verbes d'action : perd, trouve, rend).",
   "Pour chaque événement, teste : si je le retire, l'histoire reste-t-elle compréhensible ? Garde seulement les indispensables.",
   "Note les personnages indispensables (celui qui agit, celui qui aide).",
   "Rédige une ou deux phrases avec tes mots, dans l'ordre du récit.",
   "Contrôle : tout l'essentiel ? rien d'inventé ? l'ordre respecté ?"],
  "worked_example": ["Récit : « Nina perd son bonnet rouge en allant au parc. Un voisin le trouve et le lui rend. » Résumé : Nina perd son bonnet, puis un voisin le retrouve et le lui rend. La couleur du bonnet peut être retirée : elle ne change pas l'histoire.",
   "« Une tortue tombe dans un trou peu profond. Un enfant apporte une planche. La tortue grimpe et sort. » Résumé en une phrase : Un enfant aide une tortue à sortir d'un trou avec une planche. Problème, aide, résolution.",
   "« La classe prépare une exposition sur les arbres. Les élèves dessinent des feuilles et écrivent des légendes. Le vendredi, ils montrent leurs affiches aux familles. » Résumé : La classe prépare des affiches sur les arbres avec dessins et légendes. Les élèves les présentent aux familles le vendredi. Deux phrases, l'ordre du récit."],
  "common_errors": ["Recopier des phrases entières du texte : un résumé se rédige avec tes propres mots, plus courts.",
   "Garder un détail décoratif : la couleur du bonnet ou un joli sac ne changent pas la compréhension de l'histoire.",
   "Inventer ou anticiper : un résumé ne contient que ce qui est écrit — pas d'explication ajoutée ni d'opinion."]},
}


def enriched_courses():
    """Return deep copies of the 28 staged entries with enriched teaching fields."""
    enriched, missing = [], []
    for entry in COURSES:
        copy = deepcopy(entry)
        override = DEEPENINGS.get(entry["code"])
        if override is None:
            missing.append(entry["code"])
        else:
            for key, value in override.items():
                copy[key] = deepcopy(value)
        enriched.append(copy)
    if missing:
        raise ValueError(f"Leçons sans enrichissement : {sorted(missing)}")
    if len(enriched) != 28:
        raise ValueError(f"28 leçons attendues, {len(enriched)} trouvées")
    return enriched
