DROP TABLE "safety_events";
DROP TABLE "answers";
DROP TABLE "lesson_sources";
DROP TABLE "lesson_competencies";
DROP TABLE "hints";
DROP TABLE "group_members";
DROP TABLE "exercise_sources";
DROP TABLE "exercise_competencies";
DROP TABLE "exercise_attempts";
DROP TABLE "content_reviews";
DROP TABLE "consent_records";
DROP TABLE "ai_interactions";
DROP TABLE "teacher_classes";
DROP TABLE "spaced_repetition_items";
DROP TABLE "mastery_records";
DROP TABLE "lesson_versions";
DROP TABLE "learning_sessions";
DROP TABLE "learning_groups";
DROP TABLE "guardian_students";
DROP TABLE "exercise_versions";
DROP TABLE "enrollments";
DROP TABLE "content_chunks";
DROP TABLE "user_roles";
DROP TABLE "teachers";
DROP TABLE "students";
DROP TABLE "lessons";
DROP TABLE "guardians";
DROP TABLE "exercises";
DROP TABLE "content_sources";
DROP TABLE "competency_prerequisites";
DROP TABLE "classes";
DROP TABLE "audit_logs";
DROP TABLE "users";
DROP TABLE "schools";
DROP TABLE "competencies";
DROP TABLE "tenants";
DROP TABLE "subjects";
DROP TABLE "curriculum_levels";
DROP FUNCTION IF EXISTS edu_touch_updated_at();
DROP FUNCTION IF EXISTS edu_check_prerequisite_cycle();
DROP FUNCTION IF EXISTS edu_guard_version();
DROP FUNCTION IF EXISTS edu_guard_review();
DROP FUNCTION IF EXISTS edu_guard_version_child();
DROP FUNCTION IF EXISTS edu_check_consent();
DROP FUNCTION IF EXISTS edu_check_attempt();
