DROP TABLE job_dispatch;
DROP TABLE notifications;
DROP TABLE background_jobs;
DROP TABLE safety_cases;
DROP TABLE feature_flags;
DROP TABLE mission_exercises;
DROP TABLE missions;
DROP FUNCTION edu_mission_group();
REVOKE SELECT ON schools FROM edu_class,edu_analytics,edu_speech,edu_notification;
REVOKE SELECT ON user_roles FROM edu_class,edu_analytics,edu_speech,edu_notification;
REVOKE SELECT(id,tenant_id,status,auth_version,deleted_at) ON users FROM edu_class,edu_analytics,edu_speech,edu_notification;
REVOKE SELECT ON students,guardians,guardian_students,teachers,teacher_classes,enrollments FROM edu_analytics,edu_speech;
REVOKE SELECT ON teachers,teacher_classes,enrollments,learning_sessions,exercise_attempts FROM edu_notification;
REVOKE SELECT ON consent_records,student_assents FROM edu_speech;
REVOKE SELECT(id,tenant_id,status,prompt) ON exercise_versions FROM edu_speech,edu_class;
REVOKE SELECT ON exercise_competencies FROM edu_class;
REVOKE SELECT ON rag_documents FROM edu_admin;
REVOKE SELECT,INSERT ON exercises,exercise_versions,exercise_competencies,exercise_sources,hints FROM edu_notification;
REVOKE SELECT ON content_sources FROM edu_notification;
REVOKE SELECT,DELETE ON tutor_turns,safety_events,ai_interactions,audit_logs FROM edu_notification;
REVOKE UPDATE(id) ON exercise_versions FROM edu_notification;
REVOKE SELECT ON classes FROM edu_analytics;
