import type {Answers,Attempt,Exercise} from "./contracts";
export const stages=["Découverte","Explication","À toi d’essayer","Avec un coup de pouce","En autonomie","Mon bilan"] as const;
export interface Journey {stage:number;exercise:Exercise|null;attempt:Attempt|null;sessionId:string|null;answers:Answers;reasoning:Record<string,string>;busy:boolean;error:string;independentIndex:number}
export const initialJourney:Journey={stage:0,exercise:null,attempt:null,sessionId:null,answers:{},reasoning:{},busy:false,error:"",independentIndex:1};
export type JourneyAction={type:"stage";stage:number}|{type:"reasoning";id:string;value:string}|{type:"answer";id:string;value:string|string[]}|{type:"load";exercise:Exercise;attempt:Attempt;sessionId:string;stage:number;index?:number}|{type:"result";attempt:Attempt}|{type:"busy";busy:boolean}|{type:"error";error:string}|{type:"prime";exercise:Exercise;attempt:Attempt;sessionId:string};
export function journeyReducer(state:Journey,action:JourneyAction):Journey {
  switch(action.type){case "stage":return {...state,stage:action.stage,error:""};case "reasoning":return {...state,reasoning:{...state.reasoning,[action.id]:action.value}};case "answer":return {...state,answers:{...state.answers,[action.id]:action.value}};case "load":return {...state,exercise:action.exercise,attempt:action.attempt,sessionId:action.sessionId,stage:action.stage,answers:{},reasoning:{},busy:false,error:"",independentIndex:action.index??state.independentIndex};case "result":return {...state,attempt:action.attempt,busy:false};case "busy":return {...state,busy:action.busy,error:""};case "error":return {...state,error:action.error,busy:false};case "prime":return {...state,exercise:action.exercise,attempt:action.attempt,sessionId:action.sessionId};}
}
export function moveItem(items:string[],from:number,to:number){if(from<0||to<0||from>=items.length||to>=items.length)return items;const result=[...items];const [value]=result.splice(from,1);result.splice(to,0,value);return result;}
